### ISSUE TITLE
display term of use before downloading registered dataset

### ISSUE THREAD

**Issue by PapillonMcGill** [CONP-PCNO/conp-portal#112]
## Purpose
To ensure that people are aware of restriction to use registered data.

## Context
To help enforce ethics.

**Comment by xlecours** [comment]
we will display the terms of use at a visitor's first visit.
And use cookie to mark agreement

**Comment by xlecours** [comment]
- [ ] Get the term of use content (Issue : to be created)
- [ ] have a modal window that display terms of use and store a cookie; if the cookie is not sent in the request. (Issue : to be created)

**Comment by glatard** [comment]
Duplicate of #158
