### ISSUE TITLE
Zenodo vs CONP access restriction

### ISSUE THREAD

**Issue by PapillonMcGill** [CONP-PCNO/conp-portal#114]
## Purpose 
Ensure that datasets submitted to CONP through Zenodo have equivalent access restriction.
Access restriction displayed and selected on Zenodo match what is advertized on CONP.

## Context
Zenodo has different restriction on access.

**Comment by glatard** [comment]
Hi @PapillonMcGill, could you clarify what you mean by "compatible access restriction"?
