### ISSUE TITLE
Dataset presentation in portal

### ISSUE THREAD

**Issue by glatard** [CONP-PCNO/conp-portal#118]
## Purpose

The synced view of Datalad datasets in the portal is awesome! But I think it would benefit from the following improvements:
* Find a way to show logos as it was a case before. We could check if a logo.{png,jpg} file is present at the root of the dataset
* If the DATS.json model has no title, use the title of the dataset (currently, the PERFORM dataset shows as "No title in DATS.json"

**Comment by xlecours** [comment]
The second point has been addressed by having the fallback value set to the dataset submodule directory name. 
ec:
'projects/PERFORM_Dataset__one_control_subject' will have its title set to : 'PERFORM_Dataset__one_control_subject'

**Comment by xlecours** [comment]
Regarding the first point : https://github.com/CONP-PCNO/conp-dataset/issues/116

**Comment by glatard** [comment]
For the naming thing, you could also clean up the title a little bit, for instance replace underscores with spaces, etc.
