### ISSUE TITLE
Create a table of dataset with status

### ISSUE THREAD

**Issue by PapillonMcGill** [CONP-PCNO/conp-portal#153]
have 3 status:
CONP funded
Canadian dataset
External dataset (not canadian)

To be done by Naser

**Comment by glatard** [comment]
Not sure how this table will be used, but if the idea is to represent these datasets differently in the portal, it might be better to add this information to the DATS model, and have the portal parse it.

**Comment by PapillonMcGill** [comment]
It is a request by @samirdas to promote CONP funded datasets.

**Comment by xlecours** [comment]
- DATS.json now contains the information as per https://github.com/CONP-PCNO/conp-dataset/pull/149
- @liamocn is working on using that information on the portal by displaying a canadian flag for   `DATS.json::extraProperties[@category="CONP_status"].values.value` is `CONP` or `Canadian` (missing value will default to `external` which won't display the canadian flag. ) PR to be sent shortly
