### ISSUE TITLE
Write the term of use content to display

### ISSUE THREAD

**Issue by xlecours** [CONP-PCNO/conp-portal#158]
This issue is to generate the term of use to display to the user upon first visit.

@PapillonMcGill I think this should be done with Naser

**Comment by glatard** [comment]
Waiting for the terms of use.

**Comment by jbpoline** [comment]
See PR #194

**Comment by xlecours** [comment]
> See PR #194

@jbpoline #194 is not a PR but an issue

**Comment by xlecours** [comment]
Got it, #192 is the PR

**Comment by xlecours** [comment]
This is resolved.
