### ISSUE TITLE
Dataset logos can be an url

### ISSUE THREAD

**Issue by xlecours** [CONP-PCNO/conp-portal#164]
An url is a valid value for a dataset logo.
ex: PERFORM

**Comment by glatard** [comment]
another example of dataset with a URL as logo: https://portal.conp.ca/dataset?id=projects/Comparing_Perturbation_Modes_for_Evaluating_Instabilities_in_Neuroimaging__Processed_NKI_RS_Subset__08_2019_
(and all datasets crawled from Zenodo)

**Comment by cmadjar** [comment]
@glatard, @xlecours, @liamocn, @emmetaobrien  What is the status of that issue? It says this is in progress but I don't see an assignee which makes me doubt that this is actually in progress ;).

Anyone knows?

**Comment by emmetaobrien** [comment]
The DATS model can contain a url for the logo in `extraProperties->logo-> values`, as in the dataset @glatard cites above, but the portal interface is not yet picking this up and displaying it.
