### ISSUE TITLE
Dynamic study spotlight

### ISSUE THREAD

**Issue by xlecours** [CONP-PCNO/conp-portal#168]
The study spotlight on the dashboard is hardcoded as prevent-ad and the description is not dynamically generated from the DATS.json file.

1. Make the content dynamically generated
2. Should the selected study be "randomized"??

**Comment by emmetaobrien** [comment]
if I recall correctly, Alan was quite keen that we spotlight CONP datasets and particularly Prevent-AD ahead of our current set of external datasets, at least for the moment, so I would suggest keeping this as is until we start incorporating new datasets with similarly high profiles (which UK Biobank or Mousebytes may be in due course.)

**Comment by glatard** [comment]
Closing, please re-open if needed.

**Comment by cmadjar** [comment]
Discussed at the CONP dev meeting of September 30th, 2020.

Once we have the Matomo analytics working, the study spotlight could be dynamically displayed based on the number of views of the datasets between a certain interval of time. To be discussed more once we have the portal analytics setup
