### ISSUE TITLE
Numbers in the dashboard are wrong

### ISSUE THREAD

**Issue by glatard** [CONP-PCNO/conp-portal#174]
The dashboard doesn't report the right number of datasets or pipelines.

## Expected Behavior

Dashboard should report the current number of datasets and pipelines.

## Current Behavior

Pipelines are not reported. Number of datasets is wrong: it is currently 10 while the actual number of datasets is 23.
![Screenshot from 2020-02-19 10-55-12](https://user-images.githubusercontent.com/5174953/74849263-7ff6a080-5306-11ea-835a-f5dbd64a1eb4.png)

## Possible fix
If pipeline numbers are difficult to get, just drop pipelines from the dashboard. Datasets can be counted as the number of sub-modules in `conp-dataset`.

**Comment by emmetaobrien** [comment]
I would suggest removing "in 2019" from the graph header.

**Comment by liamocn** [comment]
> 
> 
> I would suggest removing "in 2019" from the graph header.

Good point :)

**Comment by xlecours** [comment]
@xlecours Let's check that

**Comment by glatard** [comment]
Since the pipelines were removed, maybe "and pipelines" could be removed from the header.

**Comment by cmadjar** [comment]
Closing this issue. The remaining title modification has been taken care of in PR #191 that was merged. Also the title issue was duplicated in issue #188 so will only keep 188 open until the changes are pulled on the portal.

Feel free to reopen if I missed something though.
