### ISSUE TITLE
[Analytics] Add Altmetric for Dataset Tracking

### ISSUE THREAD

**Issue by kchatpar** [CONP-PCNO/conp-portal#18]
Consider adding Altmetric scores next to datasets listed on the Conp website. Altmetric scores are an attention score used for tracking publications. Adding an Altmetric score next to the dataset will help the owner know where their data is being used.

Example Altmetric Score: https://www.altmetric.com/details/34049168

**Comment by xlecours** [comment]
Hi @kchatpar , can you describe the changes required to make this work?

**Comment by kchatpar** [comment]
Take this dataset for example: https://portal.conp.ca/dataset?id=projects/1000GenomesProject buttons the download, eye and heart button could be an altmetric badge. To make this happen the dataset needs a DOI and you can generate the badge here: https://www.altmetric.com/products/altmetric-badges/

**Comment by cmadjar** [comment]
You can now see the number of views per dataset and pipelines on the portal so closing this issue
