### ISSUE TITLE
Show dataset authentication status in the portal

### ISSUE THREAD

**Issue by glatard** [CONP-PCNO/conp-portal#182]
## Purpose

DATS models have recently been extended with an authorization field, that can be "public", "registered" or "private". It would be useful to represent that in the portal, with some kind of icon that could be next to the Canadian flag.

## Context

This would allow users to quickly identify which datasets can be downloaded without authentication.

**Comment by liamocn** [comment]
Can you give a better idea of the difference between 'registered' and 'private', and what type of icons you think might be suitable? I think using padlocks or security type icons might be a little heavy for an open science project.

**Comment by glatard** [comment]
* private means that you need to negotiate custom credentials with the platform hosting the data
* registered means that the dataset is accessible using a CONP portal login (not available yet)
