### ISSUE TITLE
Comprehensive search

### ISSUE THREAD

**Issue by glatard** [CONP-PCNO/conp-portal#183]
## Purpose

Several DATS fields cannot be searched from the portal. For instance, searching for "Microscopic" or "MINC" doesn't return the Big Brain dataset while these terms are in its DATS model. Search should work as a `grep` operation in all DATS models, i.e., return all the datasets containing the search string in any of the DATS fields.

## Context

It would improve the search experience in the portal.

**Comment by cmadjar** [comment]
PR merged and a comprehensive DATS searching is on the portal now.
