### ISSUE TITLE
Show portal version in portal

### ISSUE THREAD

**Issue by glatard** [CONP-PCNO/conp-portal#184]
## Purpose

The portal should display the portal version somewhere in the GUI, preferably using the first characters of the current commit, so that we know where the deployed portal stands and what features or bug fixes it is supposed to implement. 

## Context

When an issue is closed but the deployed portal doesn't seem to implement it, we have no way to check if the portal hasn't been deployed, or if the fix isn't effective.

## Possible Implementation (optional)

On portal startup, get the id of the last commit, and show it at the bottom left of the portal, in a small banner. 

## Related issues

#174, #172, #170, #162 and probably a few other issues were closed but the deployed portal doesn't have them fixed.

**Comment by cmadjar** [comment]
At the moment there is no release of the portal code, therefore no versions to be displayed. I feel like this should be closed. @glatard Thoughts?
