### ISSUE TITLE
Minor correction to graph on front page

### ISSUE THREAD

**Issue by emmetaobrien** [CONP-PCNO/conp-portal#188]
The header of the bar chart on the front page still says "Cumulative Number of Datasets and Pipelines" although it no longer contains any data for pipelines.  Also,  if there is only one set of bars, I am not sure that needs to be labelled below the graph as well as in the title and mouse-over text.

**Comment by cmadjar** [comment]
@emmetaobrien @liamocn 

It looks like this has been taken care of in the merged PR but somehow this does not show in the dashboard of the portal. Are there extra steps that need to be done for those changes to be pulled on the portal?

**Comment by emmetaobrien** [comment]
Yes; the updated portal code needs to be deployed, which I believe currently only @xlecours and @PapillonMcGill have the appropriate access to do.
