### ISSUE TITLE
Share page could use some spacing between paragraphs, too dense

### ISSUE THREAD

**Issue by cmadjar** [CONP-PCNO/conp-portal#193]
## Expected Behavior

- Spacing between section titles and paragraphs.
- Bullet lists should be represented as bullet lists.

## Current Behavior

The Share page of the CONP portal is too dense. Need spacing between paragraphs, titles etc 

Bullet point lists are not displayed as lists but stacked in the paragraph making it hard to read.

**Comment by emmetaobrien** [comment]
This is fixed in https://github.com/CONP-PCNO/conp-documentation/pull/12

**Comment by cmadjar** [comment]
@emmetaobrien I see that the Share page has been updated on the portal, however the items of lists are not shown as:
- item 1
- item 2
- item 3

but as:
item 1
item 2
item 3

Would it be possible to add bullet points in front of the list items? Could you look into it?

**Comment by emmetaobrien** [comment]
That's odd; there must be something in the css changing the default formatting for <li> tags.  I will set that specifically now.

**Comment by emmetaobrien** [comment]
Should be fixed by https://github.com/CONP-PCNO/conp-documentation/pull/19.

**Comment by cmadjar** [comment]
Thanks! Waiting to see the final results on the portal before closing this issue.

**Comment by cmadjar** [comment]
This issue is not relevant anymore. The share page will lead to the Github documentation on how to upload datasets. See #223
