### ISSUE TITLE
Documentation to be finalized for the release of the portal

### ISSUE THREAD

**Issue by cmadjar** [CONP-PCNO/conp-portal#194]
## Action items

- [x] remove the Help link at the top right of the portal
- [x] revamp the Share page to be a link to the FAQ which will all point to different documented sections

**Comment by cmadjar** [comment]
@emmetaobrien @liamocn @xlecours @glatard 
If I remember correctly, during last Wednesday's call, we discussed about the possibility to remove the WIKI page and instead have the Help link of the portal point to other documentation.
To which documentation should this points to?

Would be good to have the link correctly before the official release.

**Comment by xlecours** [comment]
I know that Santiago made a preliminary setup for readthedoc using sphynx. https://github.com/CONP-PCNO/conp-portal/tree/master/docs

**Comment by cmadjar** [comment]
Link to @emmetaobrien's FAQ PR: https://github.com/CONP-PCNO/conp-documentation/pull/15

Link to issue https://github.com/CONP-PCNO/conp-documentation/issues/16 to add pipelines and tools questions to the FAQ

**Comment by liamocn** [comment]
@cmadjar I'm a little unclear about this. Does this remove the share page and replace the 'Share' action in the sidebar with an 'FAQ' action which links externally to the FAQ?

**Comment by cmadjar** [comment]
That is what I understood from yesterday's call. @emmetaobrien Do you agree?

**Comment by emmetaobrien** [comment]
Yes, I believe that is what we are meant to do.

**Comment by cmadjar** [comment]
@emmetaobrien @liamocn @samirdas @glatard @jbpoline I just had a call with Derek and Jessica this morning and we happened to mention the portal.

Last week, during the CONP dev meeting, we all decided to remove the Share button and page and replace it with a FAQ.

Derek and Jessica strongly feel that we should keep the "Share" button/page and add an FAQ button instead. They prefer that the button is there even if we have the page that says "under construction". Looks like it would be something that Alan would want to according to them.

What do you guys think?

**Comment by 3design** [comment]
The rational to keep the share button is so that, at a glance, users can see that there is/will be a way to share their datasets and tools. 

This can still land on a placeholder page with a quick overview of what is planned (the ability to share data or tools), and a link out to the FAQ or other documentation. 

If this button isn't present, then the user may never know that this function is available or planned. This may affect how the user sees the portal: as a place to get data only, instead of a place to acquire as well as make available (in the future).

**Comment by emmetaobrien** [comment]
The logic of making that visible makes sense to me, and I suppose a button is a good way to do it.
