### ISSUE TITLE
Include "date added" and "date updated" to dataset rows

### ISSUE THREAD

**Issue by cmadjar** [CONP-PCNO/conp-portal#201]
## Purpose

There is a possibility to sort datasets by "date added" and "date updated", however, this information is not available anywhere in the dataset rows. Would be good to add those values to the dataset rows for two reasons:
- make it more intuitive for the user to see the information
- would allow us to ensure the sorting is properly done

## Context

The following was reported by Naser when he reviewed the portal before release:
- How is data sorted by “Date Added”?  I could not find any dates.  Is 1000 genomes really the first dataset added to the CONP?
- Same question for “Date Updated”.  Was the Perform dataset most recently updated?  Just to verify that all is working correctly.

**Comment by emmetaobrien** [comment]
1000GenomesProject could legitimately have the earliest date added to the current implementation of CONP dataset storage, depending on where the portal reads that from, because it was the test case I used for establishing dataset management procedures.

**Comment by cmadjar** [comment]
I can see the dates on the datasets now. Thank you @liamocn this is great! Closing the issue.
