### ISSUE TITLE
Sorting by size does not seem to work properly

### ISSUE THREAD

**Issue by cmadjar** [CONP-PCNO/conp-portal#202]
## Current Behaviour

Sorting datasets by size does not seem to work properly, datasets go from 117GB to 13.9GB (see example below in the screenshot). Many other inconsistencies found across the dataset.

## Context (optional)

This issue was reported by Naser when he reviewed the portal before release:

> Sorting by Size jumped from 117 to 13.9 GB (see below)  Lots of inconsistencies on subsequent pages.

**Comment by glatard** [comment]
Sorting by numbers should be in descending order instead of ascending order, so that the largest datasets come first.

**Comment by liamocn** [comment]
PR #205 resolves this issue
