### ISSUE TITLE
Remove sorting capabilities for Modality, Format and Source

### ISSUE THREAD

**Issue by cmadjar** [CONP-PCNO/conp-portal#205]
## Expected Behavior

Remove sorting capabilities for Modality, Format and Source. Instead add those DATS fields to the search engine so one can filter for datasets containing MINC etc...

## Context (optional)

Discussed during the CONP Dev call of March 25th.

**Comment by cmadjar** [comment]
Links to the following issue regarding adding DATS fields in the search https://github.com/CONP-PCNO/conp-portal/issues/183

**Comment by emmetaobrien** [comment]
I am at this point sure the DATS fields are consistently structured for finding this data, but there may well be places where the content is not what someone familiar with the dataset would expect, e.g. Naser mentioned SIMON and the recently generated derived BigBrain not having MRI listed as a modality.  It is straightforward for me to update any cases here; in the case of SIMON I believe @glatard is going to recrawl it soon and it would probably be better practice to generate this data at that point than for me to manually edit it.  Let me whatI should modify here.
