### ISSUE TITLE
Remove account icons from pipeline list

### ISSUE THREAD

**Issue by glatard** [CONP-PCNO/conp-portal#211]
All pipelines are public, these icons aren't necessary:
![Screenshot from 2020-03-27 08-16-30](https://user-images.githubusercontent.com/5174953/77755412-9f6aa280-7003-11ea-826c-1e18d966a84a.png)

**Comment by liamocn** [comment]
PR #215 should resolve this issue

**Comment by cmadjar** [comment]
Just checked the portal. Icons have been removed. Thanks @liamocn!!
