### ISSUE TITLE
Missing information on the dataset page that a user needs to create a LORIS account for LORIS-based datasets

### ISSUE THREAD

**Issue by cmadjar** [CONP-PCNO/conp-portal#217]
For the multi-center phantom and PREVENT-AD dataset pages, there should be an information to mention that in order to have access to those datasets, one require to request an account on their respective LORIS database and that they will be asked for that account information when downloading data through DataLad.

**Comment by cmadjar** [comment]
Will be adding those instructions via the DATS model. Add a new tag with the URL of the LORIS instance that should be clicked on to request an account.

@emmetaobrien @glatard I added the blocking release tag as this should be clarified before the release. Let's talk in the next couple of days on how to do that.

**Comment by cmadjar** [comment]
Current DATS for preventad-open (only the distributions part):
```
"distributions": [
    {
    "@id": "http://json-schema.org/draft-04/schema",
    "@type": "DatasetDistribution",
    "formats": [
      "MINC",
      "JSON"
    ],
    "size" : 174,
    "unit" : {
      "@id": "https://w3id.org/dats/schema/annotation_schema.json",
      "@type": "Annotation",
      "value": "GB"
    },
    "access": {
      "landingPage": "https://openpreventad.loris.ca",
      "authorizations": [
        {
          "value": "private"
        }
      ]
    },
    "storedIn": {
        "name": "https://openpreventad.loris.ca"
      }
    }
  ],
```

Current DATS for multicenter-phantom:
```
"distributions": [
        {
            "@type": "DatasetDistribution",
            "formats": [
                "MINC"
            ],
            "size" : 38,
            "unit" : {
                "@type": "Annotation",
                "value": "GB"
            },
            "access" : {
                "@type": "Access",
                "landingPage" : "https://phantom.loris.ca",
				"authorizations": [
					{
						"value": "private"
					}
				]
            }
        }
    ],
```

@glatard @emmetaobrien How do you suggest we modify the DATS schema to integrate a phrase in the dataset page about where to request an account for datasets requiring authorization?

**Comment by glatard** [comment]
I like the idea of just redirecting to the landing page, where all relevant infos including how to get an account would be found. So I think the portal should just display that link as the place to get an account for private datasets.

**Comment by cmadjar** [comment]
OK. So for datasets with authorizations=private, could we add a row in the dataset page:

`Request account available in the source site` ? This way it is automatic based on the DATS model (if field=private, then show that message) but a little clearer to the user that it is what they need to do.

Note: the phrasing can definitely be changed to something better. Just a suggestion for now, we'll worry about the phrasing then.

**Comment by emmetaobrien** [comment]
That sounds good to me.

**Comment by cmadjar** [comment]
@liamocn sentence to display on a dataset page with authorizations=private

Note: an account is required to access that dataset. Please following the Source URL and request an account on the source page.

@emmetaobrien does that sound fine to you?

**Comment by emmetaobrien** [comment]
I would say "this dataset" but otherwise yes, entirely.

**Comment by cmadjar** [comment]
@liamocn final sentence below:

Note: an account is required to access this dataset. Please following the Source URL and request an account on the source page.

**Comment by emmetaobrien** [comment]
"please follow", not "following"

**Comment by cmadjar** [comment]
ooops.

Note: an account is required to access this dataset. Please follow the Source URL and request an account on the source page.
