### ISSUE TITLE
Cannot download datalad datasets with loris-token on a clean install on Ubuntu

### ISSUE THREAD

**Issue by cmadjar** [CONP-PCNO/conp-portal#218]
On a brand new Ubuntu 18.04LTS VM, datasets with loris-token cannot be downloaded. The `datalad get file` command never asks for a username/password. 

Instead it gives the errors attached as a screenshot:
- for multicenter-phantom dataset
![Screen Shot 2020-03-30 at 4 57 29 PM](https://user-images.githubusercontent.com/1402456/78057863-65780400-7355-11ea-933a-7c013e12e50e.png)

- for preventad-open
![Screen Shot 2020-03-31 at 1 43 45 PM](https://user-images.githubusercontent.com/1402456/78058024-ae2fbd00-7355-11ea-8cc9-e192833b76c8.png)

**Comment by cmadjar** [comment]
Not sure this is the right repo for the bug.

**Comment by glatard** [comment]
@mathdugre, do you know how to make sure that datalad logs in to LORIS?

**Comment by cmadjar** [comment]
Looks like the issue I was having was due to the fact that the default datalad version installed on Ubuntu using `sudo apt-get install datalad` is 0.9.3. Looks like the loris-token part of datalad was developed after that version and fully functional as of v0.11.4 of datalad.

Updated the install on my Ubuntu machine by installing datalad via Miniconda and that fixed the issue since the version of datalad was upgrade to 0.12.3.

In the following PR: https://github.com/CONP-PCNO/conp-documentation/pull/24; I added documentation to the FAQ pertinent to the two datasets that require a loris-token (a.k.a. multicenter-phantom and preventad-open).

We should probably add in all dataset pages that at least version 0.12.2 of datalad is required. Any thoughts?

**Comment by jbpoline** [comment]
Hi @cmadjar : which version of ubuntu ? see below with a fresh install on 18.04 (the current LTS)

t-jb:~$ sudo apt-get install datalad
[sudo] password for jb: 
Reading package lists... Done
[....install ... ]
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
t-jb:~$ datalad --version
datalad 0.12.4
t-jb:~$ git-annex version
git-annex version: 7.20190819+git2-g908476a9b-1~ndall+1
[....]
t-jb:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic

**Comment by cmadjar** [comment]
I did the install on ubuntu 18.04LTS using `sudo apt-get install datalad` like you but instead got DataLad version 0.9.3.
Not sure why we get different versions with the same system.

![Screen Shot 2020-04-01 at 8 22 27 AM](https://user-images.githubusercontent.com/1402456/78136700-1502b400-73f2-11ea-82d7-09132ed75f09.png)
![Screen Shot 2020-04-01 at 8 22 41 AM](https://user-images.githubusercontent.com/1402456/78136701-1502b400-73f2-11ea-8b66-de760b96a696.png)
![Screen Shot 2020-04-01 at 8 23 04 AM](https://user-images.githubusercontent.com/1402456/78136704-1502b400-73f2-11ea-9aad-4b91a69c8fb7.png)
 
 In order to install version 0.12.3 I had to do that through Miniconda.

**Comment by cmadjar** [comment]
Created an issue on the DataLad handbook repository as this is more related to DataLad install than the portal. Link to the issue: https://github.com/datalad-handbook/book/issues/441.

in the meantime, documentation was added in the FAQ regarding the need to have version 0.12.2 or higher of DataLad installed in order to download datasets with loris-token. Closing this issue for now. To be followed on the DataLad repo.

**Comment by cmadjar** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Duplicate dataset issue (300)](https://trello.com/c/NO3X3NXT/5-duplicate-dataset-issue-300)

**Comment by cmadjar** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Duplicate dataset issue (300)](https://trello.com/c/NO3X3NXT/5-duplicate-dataset-issue-300)
