### ISSUE TITLE
No results show when searching on pages other than page 1

### ISSUE THREAD

**Issue by 3design** [CONP-PCNO/conp-portal#228]
On the dataset search page, typing a search parameter does not show entries if you are not on page 1

## Expected Behavior

1. go to data page
2. enter in search parameter
3. relevant datasets are shown

## Current Behavior

1. go to data page
2. enter in search parameter
3. relevant datasets are shown

1. go to data page
2. go to page 2 (or 3) of results
3. enter in search parameter
4. no results shown

## Possible fix (optional)

just a guess: the search bar is a live filter of existing results (all), as opposed to an entry that is used to query the database

**Comment by cmadjar** [comment]
@3design Thank you so much for reporting the issue. I just merged the code on the repo. You should see the changes on the portal in less than an hour.

@liamocn thank you for fixing the issue.

FYI - I leave the issue open until I can confirm that this behaviour was pulled on the portal :).

**Comment by cmadjar** [comment]
All fixed.
