### ISSUE TITLE
Redesign the tools & pipelines page

### ISSUE THREAD

**Issue by cmadjar** [CONP-PCNO/conp-portal#242]
The Tools & Pipelines page should be redesigned to be similar to the way data are organized:

- the landing page would list the pipelines and tools and users could click on specific tools which will redirect to a detailed tool page. The summary information displayed in the pipeline row could be the following from the Boutiques Schema:

  - description, truncated to the first X character
  - name
  - tags
  - zenodo id / doi

- create a detailed too page that would read the Boutiques Schema and display at least those information:

  - author
  - container-image (en particulier le type, pour savoir si c'est Docker ou Singularity)
  - description
  - descriptor-url
  - doi / zenodo id
  - name
  - online-platform-urls (c'est ce qui est derrière le cbrain button)
  - tags
  - tool-doi
  - tool-version
  - tool-url

In addition, in the detailed page, we should add clear instructions on how to run the tools with also clear links to the Boutiques Tutorial

Link to other issues regarding the design of the tools & pipelines page:
- https://github.com/CONP-PCNO/conp-portal/issues/229
- https://github.com/CONP-PCNO/conp-portal/issues/224
- https://github.com/CONP-PCNO/conp-portal/issues/209
- https://github.com/CONP-PCNO/conp-portal/issues/208

**Comment by glatard** [comment]
Link to the Boutiques schema doc: https://github.com/boutiques/boutiques/tree/master/schema

**Comment by cmadjar** [comment]
Link to the sketch of the website that was done by Derek and Santiago a year ago. We could probably start from that and build on top of it. To be discussed in a meeting early next week.

https://sketch.cloud/s/mOnl8 

**a few notes and quick ideas:** 
- make the tools page like the data page (list of rows) with the information mentioned in the description of this issue (including tool logos when provided otherwise default wheels logo, icon grey/blue to run on CBRAIN, URL to the tool...) 
  Also ensure to include the number of rows in the data table so users know how many tools are available easily 
- in the detailed page
  - short instructions on how to run this locally (with links to Boutiques tutorial)
  - run on CBRAIN button
  - URL to the tool
  - Zenodo URL
  - detailed list mentioned on the description of this ticket
  - dated added, and date updated if that information is easily findable?

**Comment by glatard** [comment]
I think the 1st page should contain the following info:
-     description, truncated to the first X character
-     name
-     tags
-     zenodo id / doi
-    cbrain button

Before we meet, I'd suggest that someone drafts a mock interface so that we have something concrete to discuss from.

**Comment by glatard** [comment]
Just to clarify, I think the mockup from Derek linked by @cmadjar above looks very good: I would just replace "tool type" by tags on the first page.

**Comment by cmadjar** [comment]
@3design for the detailed page of tools, could you modify the sketch as follows?

- in the top container with the pipeline title, repeat the information from the cards in the list page:
  - name (a.k.a. the title)
  - tags
  - zenodo id / doi

- the line with the three containers:
  - first container (Run Locally):
    - modify the description to be "This tool can be run from any system using Boutiques and a container engine "
    - modify the link to "click here for instructions" which will scroll down the page to the instruction section
  - second container (Run on CONP cloud):
    - I think CBRAIN should be all upper case
    - Remove the "Export and", just keep "Run on CBRAIN platform"
  - third container:
    - **### I am not sure yet what to do about that container. TBD later**
 
- display of the following information (that would be derived from the [Boutiques schema](https://github.com/boutiques/boutiques/tree/master/schema)):
  - author
  - tool-url
  - description
  - descriptor-url
  - container-image (en particulier le type, pour savoir si c'est Docker ou Singularity)
  - online-platform-urls (c'est ce qui est derrière le cbrain button)
  - tool-doi
  - tool-version

- add a section with instructions on how to run the tool locally using Boutiques



Display of the instruction section:

### Instructions on how to run the tool locally

CONP pipelines can be easily installed and run on any computer with a container engine. The preferred container for the tool is available in the container-image field above. For detailed information on how to use Boutiques, please visit [this tutorial](https://nbviewer.jupyter.org/github/boutiques/tutorial/blob/master/notebooks/boutiques-tutorial.ipynb#reusing_tools). 

1) list the inputs/outputs needed for the pipeline to run
```
bosh example zenodo.#id
```
Note: this command will list only the required options to run the pipeline. To view the complete list of options, use `bosh example --complete zenodo.#id`

2) create an invocation JSON file based on the output of `bosh example`

3) run the pipeline with the invocation JSON file created in 2)
```
bosh exec launch -s zenodo.#id ./invocation.json -v /data:/data
```
Note: the option `-s` will show STDERR, STDOUT in the terminal. The option `-v` allows mounting a directory from your system onto the container engine.

Thank you!

**Comment by 3design** [comment]
Updated

https://www.sketch.com/s/mOnl8

https://www.sketch.com/s/mOnl8/a/dq3g22

**Comment by cmadjar** [comment]
Nice! Thank you @3design!!

The only thing I would change is the way the instructions title and the instructions themselves are displayed so the page would look like somthing like that.
 _______________________________________________________
| run locally | run on CBRAIN | run on other platform |
________________________________________________________

| authors: | bla bli |
| URL: | url |
| Description: |bla bli blu |
etc...
 _________________________________________________________
#### Instructions on how to run the tool locally

This is the instructions to follow, blablabla...

Kind of have a differentiation between the instructions and the pipeline details. Am I making any sense?

**Comment by glatard** [comment]
Sounds like this is ready for @liamocn to implement, do you confirm @cmadjar ?

**Comment by cmadjar** [comment]
@glatard yes, I think it is ready for @liamocn
