### ISSUE TITLE
Make the dataset download instructions more user-friendly

### ISSUE THREAD

**Issue by cmadjar** [CONP-PCNO/conp-portal#245]
While all the correct information is present in the dataset page, need to make the download instruction a bit more user-friendly:
- explicitly mention that in order to download the dataset, users need to have basic understanding of UNIX command lines
- explicitly mention that in order to download the dataset, users need to install DataLad
- explain to the user what the different commands do and what to expect from those commands
- display the README.md on the dataset page, those README would contain information that datasets people think important to understand what their dataset is about and how it is organized.

Will start drafting the page in that ticket later on and seek feedback before going into development phase. Assigning it to me for now.

**Comment by cmadjar** [comment]
![Screen Shot 2020-04-08 at 4 38 51 PM](https://user-images.githubusercontent.com/1402456/78831341-74932d80-79b7-11ea-9f80-ed7132607ffd.png)


### Dataset Download Instructions

![Screen Shot 2020-04-08 at 4 39 37 PM](https://user-images.githubusercontent.com/1402456/78831395-912f6580-79b7-11ea-9de0-5a08f8244ddd.png)

The following instructions requires to have a basic understanding of UNIX command lines. We are currently working on a way to download the dataset via a button on the browser for easier download.

Dataset download is enabled through [DataLad](https://www.datalad.org/). To install DataLad on your system, please refer to the [install section of the DataLad Handbook.](http://handbook.datalad.org/en/latest/intro/installation.html#install). Installation via `miniconda` is recommended in order to obtain the latest version of DataLad. 

To initiate the CONP dataset (`conp-dataset`), run the following command in the directory where you want CONP datasets to be installed:
```
datalad install https://github.com/CONP-PCNO/conp-dataset.git
```

To install the dataset, go into the created `conp-dataset` directory and run `datalad install` on the dataset:
```
cd conp-dataset
datalad install projects/**DATASETNAME**
```

Now that the DataLad dataset has been installed, go into the dataset directory under `projects/**DATASETNAME**`. 
```
cd projects/**DATASETNAME**
```

Note that files present in the dataset directly are symlinks and will need to be downloaded manually using the `datalad get <filepath>` command in the dataset directory:
```
datalad get <filepath>
```
Note, if you run `datalad get *` command, all the files present in the dataset directory will be downloaded. 

For more information on how DataLad works, please visit the [DataLad Handbook documentation](http://handbook.datalad.org/en/latest/).


### Dataset README information

**_DISPLAY CONTENT OF THE README ATTACHED TO THE DATASET_**

**Comment by cmadjar** [comment]
@samirdas what do you think?

**Comment by emmetaobrien** [comment]
I suggest cutting "to have" in the first paragraph, "requires a basic understanding" is clear and reads better.

**Comment by cmadjar** [comment]
@emmetaobrien applied your suggestion in the text above. Thanks!

**Comment by samirdas** [comment]
I've made some minor edits below to the text:

The following instructions require a basic understanding of UNIX/LINUX command lines. Future portal functionality may include downloads directly from the web browser. Dataset download is currently enabled through DataLad. 

To install DataLad on your system, please refer to the install section of the DataLad Handbook. Installation via miniconda is recommended in order to obtain the latest version of DataLad.

To initiate the CONP dataset (conp-dataset), run the following command in the directory where you want CONP datasets to be installed:

datalad install https://github.com/CONP-PCNO/conp-dataset.git

To install the dataset, go into the created conp-dataset directory and run datalad install on the dataset:

cd conp-dataset
datalad install projects/**DATASETNAME**

Now that the DataLad dataset has been installed, go into the dataset directory under projects/**DATASETNAME**.

cd projects/**DATASETNAME**

Note that files visible in the dataset are symlinks and will need to be downloaded manually using the datalad get <filepath> command in the dataset directory:

datalad get <filepath> 
Note, if you run datalad get * command, all the files present in the dataset directory will be downloaded.

For more information on how DataLad works, please visit the DataLad Handbook documentation.

**Comment by cmadjar** [comment]
@liamocn could you modify the detailed dataset page to match the following?

![Screen Shot 2020-04-08 at 4 38 51 PM](https://user-images.githubusercontent.com/1402456/78831341-74932d80-79b7-11ea-9f80-ed7132607ffd.png)


### Dataset Download Instructions

![Screen Shot 2020-04-08 at 4 39 37 PM](https://user-images.githubusercontent.com/1402456/78831395-912f6580-79b7-11ea-9de0-5a08f8244ddd.png)

The following instructions require a basic understanding of UNIX/LINUX command lines. Future portal functionality may include downloads directly from the web browser. Dataset download is currently enabled through [DataLad](https://www.datalad.org/).

To install DataLad on your system, please refer to the [install section of the DataLad Handbook](http://handbook.datalad.org/en/latest/intro/installation.html#install). Installation via `miniconda` is recommended in order to obtain the latest version of DataLad.

To initiate the CONP dataset (`conp-dataset`), run the following command in the directory where you want CONP datasets to be installed:
```
datalad install https://github.com/CONP-PCNO/conp-dataset.git
```

To install the dataset, go into the created `conp-dataset` directory and run `datalad install` on the dataset:
```
cd conp-dataset
datalad install projects/**DATASETNAME**
```

Now that the DataLad dataset has been installed, go into the dataset directory under `projects/**DATASETNAME**`. 
```
cd projects/**DATASETNAME**
```

Note that files visible in the dataset are symlinks and will need to be downloaded manually using the `datalad get` command in the dataset directory:
```
datalad get <filepath>
```
Note, if you run `datalad get *` command, all the files present in the dataset directory will be downloaded. 

For more information on how DataLad works, please visit the [DataLad Handbook documentation](http://handbook.datalad.org/en/latest/).


### Dataset README information

**_DISPLAY CONTENT OF THE README ATTACHED TO THE DATASET_**

**Comment by cmadjar** [comment]
The documentation part was merged. Only things left to do on that ticket is display the README.md at the end of the page with section title "Dataset README information".
