### ISSUE TITLE
Add pipelines statistics to the dashboard

### ISSUE THREAD

**Issue by cmadjar** [CONP-PCNO/conp-portal#248]
## Purpose

Need to add pipeline statistics to the dashboard to get a first glance idea of what is there.

## Context

This was brought up during the demo to Alan

**Comment by glatard** [comment]
@liamocn is there any particular issue regarding this?

**Comment by liamocn** [comment]
@glatard Yes, the issue before was that the data model for pipelines didn't allow for making the calculations. Has this changed?

**Comment by glatard** [comment]
not that I know: would "date added" for each pipeline be enough, or do you need anything else?

**Comment by liamocn** [comment]
@glatard Yes that would be enough, but it doesn't seem to be there currently.

**Comment by glatard** [comment]
OK, this requires extending the Boutiques client, and checking if this information is returned by the Zenodo API. See Boutiques issue linked just above.

**Comment by liamocn** [comment]
@glatard Do I need to wait for the latest version of boutiques for this?

**Comment by glatard** [comment]
yes, https://github.com/boutiques/boutiques/issues/604 has been implemented and merged to `dev` -- it will be available in the next release. It should come soon now.

**Comment by liamocn** [comment]
Great, thanks!

**Comment by glatard** [comment]
Hi @liamocn, the new Boutiques release (0.5.25) now reports pipeline upload date, you can update with `pip install -U boutiques`. I'm not sure how the upload dates will be grabbed, but it might be easier through the Python API than from the CLI. Let me know if anything is unclear!

**Comment by liamocn** [comment]
Thanks @glatard !
