### ISSUE TITLE
Sort function: explain what each criterion means

### ISSUE THREAD

**Issue by cmadjar** [CONP-PCNO/conp-portal#252]
For instance, Size might mean the number of subjects or number of files but it actually means total disk space. etc...

## Context (optional)

Alan's feedback

**Comment by cmadjar** [comment]
In the datasets page, the following should be relabelled:

- origin -> ?, not sure what that means actually...
- title -> dataset name
- size -> disk space usage
- files -> number of files
- subjects -> number of subjects
- format -> file format

**Comment by liamocn** [comment]
'Origin' refers to whether the datasets are canadian, external etc.
