### ISSUE TITLE
Need to add PI and succinct dataset description to the list page or the dataset page?

### ISSUE THREAD

**Issue by cmadjar** [CONP-PCNO/conp-portal#254]
We need some information for every dataset about who is the PI (or PIs) and a succinct description of this dataset, not just a data source.

## Context (optional)

Alan's feedback

**Comment by glatard** [comment]
This requires adding the PI to the DATS model, finding the information and updating all DATS models. This requires @emmetaobrien's help.

**Comment by emmetaobrien** [comment]
The most straightforward way to do this appears to be by using the `roles` property in the DATS person schema, which we can attach to any person already in a DATS model under `creators`; I would assigning a standard value of "Principal Investigator" as a role for the appropriate individual. This will work for most of the datasets; there are cases where equivalent information is not immediately to hand because the listed creator/author is an organisation (e.g. the 1000 Genomes Project).

**Comment by emmetaobrien** [comment]
A sample DATS model with this property added is included in https://github.com/CONP-PCNO/conp-dataset/pull/256.

**Comment by cmadjar** [comment]
Note: once merged, this information derived from the DATS models will need to be displayed both in the list of datasets and the dataset pages.

**Comment by cmadjar** [comment]
Question: could there be more than one PI (for example for a study that was started by one researcher and then taken over by another research upon retirement of the first one?)

**Comment by emmetaobrien** [comment]
If we want to allow that my implementation supports it; there is no existing structured way of distinguishing different PIs like that (or distinguishing that case from co-PIs, for example)  but we could annotate that within the value of `creators->names->roles`.

**Comment by cmadjar** [comment]
@emmetaobrien what is left to be done for this ticket now that the DATS model was updated? Are the datasets updated? 
Is this ready to add that information on the portal?

Thank you!

**Comment by emmetaobrien** [comment]
Some of the datasets are updated.  @joeyzhou98 is going to implement code to check whether a dataset has a defined Project Leader in Zenodo, and if so, annotate that person as PI in the DATS.json file (either by finding a match or by creating a new entry under `creators`.  Once this is done, we will need to reprocess the datasets created by conp-bot.

**Comment by cmadjar** [comment]
@liamocn can you work on adding the PI and small description of the dataset to the dataset list page and dataset page?

Thank you!
