### ISSUE TITLE
Datasets update broken

### ISSUE THREAD

**Issue by xlecours** [CONP-PCNO/conp-portal#270]
There is a new dataset in conp-dataset with a long name. here is the error log of `flask update_datasets`

`
sqlalchemy.exc.DataError: (pymysql.err.DataError) (1406, "Data too long for column 'dataset_id' at row 1")`

**Comment by glatard** [comment]
Are there any news about this? Two datasets were added recently and don't seem to show in the portal, this is a bit embarrassing.

**Comment by cmadjar** [comment]
That is not good... Who could this be assigned to? I am not sure who is the best to tackle that one.

**Comment by glatard** [comment]
Thanks @liamocn for taking this on!

**Comment by liamocn** [comment]
@glatard @xlecours @cmadjar OK, there's a PR in for this now. I believe `flask db upgrade` will need to be ran on the production server which I don't have access to. Regarding the datasets which failed, it's very possible they will be considered 'installed' by the update_datasets script even though inserting the records failed, though I'm not 100% sure. In that case, removing the datasets directory entirely and cloning it fresh is recommended.

**Comment by cmadjar** [comment]
@liamocn @xlecours I tried running `flask db upgrade` on the production server but got the following error:
```
conp-admin@portal:~/conp-portal$ flask run upgrade

Command 'flask' not found, but can be installed with:

apt install python3-flask
Please ask your administrator.
```

I am surprised flask is not installed on production. @xlecours Would you mind taking a look at production for that? J'ose pas, LOL. Can't wait to have a dev version of the portal so I would not feel too stressed about messing up ;).

**Comment by liamocn** [comment]
@cmadjar It sounds like you didn't activate the python environment, with `source venv/bin/activate`

**Comment by cmadjar** [comment]
ooops, right. Did not think of it... I did run `flask db upgrade`. Not sure what to expect from then though

**Comment by glatard** [comment]
Hi, are there updates about this? The portal still doesn't seem to have the new datasets.

**Comment by cmadjar** [comment]
@liamocn will look at what is going on on the portal.

Access to the portal.conp.ca VM has been asked for Liam: https://redmine.cbrain.mcgill.ca/issues/17864

**Comment by liamocn** [comment]
I migrated the production db to latest revision (though there were some issues with the migration scripts) and updates the datasets:

`(venv) conp-admin@portal:~/conp-portal$ flask update_datasets
[INFO   ] Installing <Dataset path=/data/not_backed_up/conp-portal/data/conp-dataset> underneath /data/not_backed_up/conp-portal/data/conp-dataset recursively
[INFO   ] conp-dataset update complete
[INFO   ] Updating subdatasets
[INFO   ] Updating https://github.com/emmetaobrien/1000GenomesProject.git
[INFO   ] projects/1000GenomesProject updated.
[INFO   ] Updating https://github.com/conpdatasets/bigbrain-datalad.git
[INFO   ] projects/bigbrain-datalad updated.
[INFO   ] Updating https://github.com/emmetaobrien/BigBrain_3DClassifiedVolumes.git
[INFO   ] projects/BigBrain_3DClassifiedVolumes updated.
[INFO   ] Updating https://github.com/emmetaobrien/BigBrain_3DSurfaces.git
[INFO   ] projects/BigBrain_3DSurfaces updated.
[INFO   ] Updating https://github.com/conpdatasets/Brainspan.git
[INFO   ] projects/Brainspan updated.
[INFO   ] Updating https://github.com/conp-bot/conp-dataset-Comparing-Perturbation-Modes-for-Evaluating-Instabilities-in-Neuroimaging-Processed-NK.git
[INFO   ] projects/Comparing_Perturbation_Modes_for_Evaluating_Instabilities_in_Neuroimaging__Processed_NKI_RS_Subset__08_2019_ updated.
[INFO   ] Updating https://github.com/conp-bot/conp-dataset-Intracellular-Recordings-of-Murine-Neocortical-Neurons.git
[INFO   ] projects/Intracellular_Recordings_of_Murine_Neocortical_Neurons updated.
[INFO   ] Updating https://github.com/conpdatasets/BigBrainHippoUnfold.git
[INFO   ] projects/Khanlab/BigBrainHippoUnfold updated.
[INFO   ] Updating https://github.com/conpdatasets/BigBrainMRICoreg.git
[INFO   ] projects/Khanlab/BigBrainMRICoreg updated.
[INFO   ] Updating https://github.com/emmetaobrien/HCPUR100-Template.git
[INFO   ] projects/Khanlab/HCPUR100-Template updated.
[INFO   ] Updating https://github.com/conp-bot/conp-dataset-Learning_Naturalistic_Structure__Processed_fMRI_dataset.git
[INFO   ] projects/Learning_Naturalistic_Structure__Processed_fMRI_dataset updated.
[INFO   ] Updating https://github.com/conp-bot/conp-dataset-MRI_and_unbiased_averages_of_wild_muskrats__Ondatra_zibethicus__and_red_squirrels__Tami.git
[INFO   ] projects/MRI_and_unbiased_averages_of_wild_muskrats__Ondatra_zibethicus__and_red_squirrels__Tamiasciurus_hudsonicus_ updated.
[INFO   ] Updating https://github.com/conp-bot/conp-dataset-PERFORM_Dataset__one_control_subject.git
[INFO   ] projects/PERFORM_Dataset__one_control_subject updated.
[INFO   ] Updating http://github.com/gi114/Reusing-Neuro-Data.git
[INFO   ] projects/Reusing-Neuro-Data updated.
[INFO   ] Updating https://github.com/conpdatasets/SIMON-dataset.git
[INFO   ] projects/SIMON-dataset updated.
[INFO   ] Updating https://github.com/conp-bot/conp-dataset-VFA_T1_mapping___RTHawk__open__vs_Siemens__commercial_.git
[INFO   ] projects/VFA_T1_mapping___RTHawk__open__vs_Siemens__commercial_ updated.
[INFO   ] Updating https://github.com/conpdatasets/celltypes.git
[INFO   ] projects/celltypes updated.
[INFO   ] Updating https://github.com/zxenia/mcgill-emc-rna-seq-experiment.git
[INFO   ] projects/mcgill-emc-rna-seq-experiment updated.
[INFO   ] Updating https://github.com/conpdatasets/mm_neo_atlas.git
[INFO   ] projects/mm_neo_atlas updated.
[INFO   ] Updating https://github.com/emmetaobrien/multicenter-phantom.git
[INFO   ] projects/multicenter-phantom updated.
[INFO   ] Updating https://github.com/conpdatasets/nhpatlas.git
[INFO   ] projects/nhpatlas updated.
[INFO   ] Updating https://github.com/conpdatasets/openpain-BrainNetworkChange_Mano.git
[INFO   ] openpain-BrainNetworkChange_Mano updated.
[INFO   ] Updating https://github.com/conpdatasets/openpain-cbp_resting.git
[INFO   ] openpain-cbp_resting updated.
[INFO   ] Updating https://github.com/conpdatasets/openpain-placebo_1.git
[INFO   ] openpain-placebo_1 updated.
[INFO   ] Updating https://github.com/conpdatasets/openpain-placebo_predict_tetreault.git
[INFO   ] openpain-placebo_predict_tetreault updated.
[INFO   ] Updating https://github.com/conpdatasets/openpain-subacute_longitudinal_study.git
[INFO   ] openpain-subacute_longitudinal_study updated.
[INFO   ] Updating https://github.com/conpdatasets/openpain-thermal.git
[INFO   ] openpain-thermal updated.
[INFO   ] Updating https://github.com/conpdatasets/preventad-open.git
[INFO   ] projects/preventad-open updated.
[INFO   ] Updating https://github.com/emmetaobrien/refseq_Callithrix_jacchus.git
[INFO   ] projects/refseq/refseq_Callithrix_jacchus updated.
[INFO   ] Updating https://github.com/emmetaobrien/refseq_Homo_sapiens.git
[INFO   ] projects/refseq/refseq_Homo_sapiens updated.
[INFO   ] Updating https://github.com/emmetaobrien/refseq_Mus_musculus.git
[INFO   ] projects/refseq/refseq_Mus_musculus updated.
[INFO   ] Updating https://github.com/conpdatasets/ds001634.git
[INFO   ] projects/ds001634 updated.
[INFO   ] Updating https://github.com/CONP-PCNO/schema.git

[ERROR  ] DATS.json file can`t be found in /data/not_backed_up/conp-portal/data/conp-dataset/scripts/dats_validator/conp-dats.`
