### ISSUE TITLE
Integration of additional sharing platforms

### ISSUE THREAD

**Issue by cmadjar** [CONP-PCNO/conp-portal#281]
## Purpose

This was brought up as a feedback from the webinar. 

Simpler integration with other platforms. Very impressed that it can interface with Zenodo, OSF, and Datalad though.

**Comment by cmadjar** [comment]
FRDR will be added shortly. Already cover a lot of useful sharing platform.

Could also add Google Drive eventually.

**Comment by cmadjar** [comment]
For now, we will focus on what we provide already and improve it. (OSF, Zenodo, FRDR)

**Comment by jbpoline** [comment]
@cmadjar : One big one will be DataVerse : it has already be "blessed" by mcgill and is increasingly used
