### ISSUE TITLE
Download button

### ISSUE THREAD

**Issue by cmadjar** [CONP-PCNO/conp-portal#283]
## Purpose

Have a download button for easier download.

## Proposed download workflow (from the WIKI page that will be removed in favour of this issue)

This draft specifies a data download mechanism from the CONP portal. This mechanism would be an alternate to using the DataLad client in situations where it cannot be easily used.

The following download workflow is proposed:
1. User clicks on dataset download link
2. Browser queries the server for list of URLs in the dataset
3. Server uses DataLad/git-annex to retrieve the list of URLs associated with the dataset files. As this operation might take some time, the use of a caching mechanism is suggested
4. Client downloads the URLs returned by the server

This workflow has the following desirable properties compared to a centralized solution where the portal would download all the data and serve it to the users:
1. No network performance bottleneck in the portal
2. No need for extensive data storage in the portal
3. No need to store user credentials in the portal
4. Possibility to track downloads in the portal

Technical notes:
1. Downloading multiple files from the browser requires the use of web-workers.
2. Cross domain data access requires that the data server authorizes cross-domain queries. This will have to be configured in data providers. 
3. We should make sure that the URLs associated with the data files use a protocol that can be accessible by a browser. It is proposed to agree on a list of protocols (e.g., http, ftp, grid FTP, s3) that the dataset can use, and to specify the list of protocols used in the DATS model.
4. The user should be warned about the size of the dataset when it's too big. Size can be obtained from the DATS model.
5. The browser should group files in an archive when there are many
6. User should be able to select/download only a subset of the files
7. If storage space is available, the portal could cache some files on the server and serve them directly
8. Downloader could send a download confirmation and summary to the portal for tracking purposes

Feedback from DataLad developers. Suggestion: look how OpenNeuro does it:
  - https://github.com/OpenNeuroOrg/openneuro/blob/eff90d7e7fd61b858d43d8f2c73918eff0a32ac4/packages/openneuro-app/src/scripts/datalad/download/download-dataset.jsx
  - https://github.com/OpenNeuroOrg/openneuro/blob/db32c348b991aa3b4e98c88bb51d5c9ffc084019/packages/openneuro-app/src/scripts/datalad/download/download-sw.js#L59:30

Received feedback and approval from TSC (discussed at Feb 3rd, 2020 meeting)

**Comment by glatard** [comment]
See initial specification at https://github.com/CONP-PCNO/conp-portal/wiki/Data-download-mechanism-from-CONP-portal

**Comment by cmadjar** [comment]
Probably partly related to https://github.com/CONP-PCNO/conp-portal/issues/96

**Comment by cmadjar** [comment]
@xlecours @liamocn can you guys start working on that.

Xavier has already started thinking about the process. Liam, could you take the lead on that and work with Xavier to implement this? Xavier will be there to consult on how to do that but the bulk of the work would be done by Liam.

Target date to have that complete would be end of August.

Does that work for you guys?

**Comment by cmadjar** [comment]
Will reconvene when @glatard comes back from vacation on the week of August 17th. 

In the meantime let's investigate more:

- @xlecours  will look into the DQT workers: 
  - the workers gets the files from URLs and zip them in the user's browser
  - will be limited by the size the browser allows as download, which might be a couple of GB...

- @emmetaobrien to look at how OpenNeuro does that 

- @liamocn to investigate other possibilities on how to do the Download and be able to resume the download if it gets interrupted

**Comment by cmadjar** [comment]
One solution was FTP sites but not secure so not investigating that option further for now...

Could not find a solution to download at the individual files level unfortunately... 


**Proposal so far unless there is a better idea:**
- for each project create a tarball on a centralized server
- could show the progress of the streaming of the tarball 
- if the download is interrupted, it will pick up where it stopped 
- there exists some javascript libraries that can probably do that
- limited to small datasets (under 20GB probably? Need to investigate the size limit there) Probably 3/4 of the datasets will be eligible to the download button in that case
- could automate the way the tarball is created whenever the dataset is updated
- will need to sync authentication with external accounts required to access the data if needed

Note: 
- 28 out of 38 datasets are below 25GB of size
- phantom dataset is ~50GB
- other 9 datasets are over 100GB

@glatard @xlecours do you have a better solution? Let us know your thoughts. Thanks!

**Comment by xlecours** [comment]
For the ones that are truly open, Academic torrent would be an elegant, file by file solution.

**Comment by emmetaobrien** [comment]
i tested academic torrent on the 1000 Genomes dataset about a year ago and found downloading slow and unreliable.

**Comment by xlecours** [comment]
> i tested academictorrent on the 1000 Genomes dataset about a year ago and found downloading slow and unreliable.

Was it via gitannex?

**Comment by emmetaobrien** [comment]
I would have to check my notes.  I remember it being slow and unreliable on bittorrent interfaces anyway.

**Comment by glatard** [comment]
Hi everyone, sorry for joining the discussion late. At some point we had designed a solution where the server would return datalad urls to the client, and the client would download them from their hosting sites, pending cross-origin issues. Is there an obvious issue with this solution? Compared to the centralized solution described above, it would:
* Avoid authorization issues, as the data would still be downloaded from the hosting centers
* Avoid having to maintain an up-to-date tarball of each dataset (checking updates, etc)
* Allow users to select and download only a subset of files

We had described this solution a few months ago on the wiki:
https://github.com/CONP-PCNO/conp-portal/wiki/Data-download-mechanism-from-CONP-portal
(unfortunately this page was deleted)0

**Comment by cmadjar** [comment]
Note: the description @glatard is mentioning has been copied to the description of the issue above for information before deleting the WIKI page.

@liamocn @xlecours @emmetaobrien Any thoughts on what @glatard mentioned on August 26th?

**Comment by liamocn** [comment]
I think this would be a better solution than tarballs, but the cross-origin issues are significant. The CORS policies on the hosting sites are something we don't have control over and as such I'm not sure we can guarantee that the files of the dataset(s) would be accessible to the user through the portal. Of course we could return those urls to the user, but then this becomes less of a 'download button' and more of a download manager where the user can simply account for the files in the dataset, where they are and how to get them.

**Comment by glatard** [comment]
did you have the chance to look at how OpenNeuro does it? It seems that they have a web downloader:
-    https://github.com/OpenNeuroOrg/openneuro/blob/eff90d7e7fd61b858d43d8f2c73918eff0a32ac4/packages/openneuro-app/src/scripts/datalad/download/download-dataset.jsx
-    https://github.com/OpenNeuroOrg/openneuro/blob/db32c348b991aa3b4e98c88bb51d5c9ffc084019/packages/openneuro-app/src/scripts/datalad/download/download-sw.js#L59:30

**Comment by glatard** [comment]
Here is the plan discussed at our meeting today:

1. If dataset requires AUTHENTICATION or is TOO BIG (size threshold to be configured in portal properties):

- Don't show download button, revert to download with Datalad

2. When user clicks on download button **for a given dataset version** (DV):

- Server checks if a zip file already exists for this version.
- If zip file doesn't exist:
   - Check for available storage space (AST) on partition holding the dataset
- if AST < size(DV) + margin:  # margin is a config param of the portal, defined to avoid completely saturating disk partitions
   - Delete files (datalad and zip) from least-recently used datasets untill ASST is enough
- Download DV using Datalad
- Create zip file, name it after DV
- Send zip file to client, return

@liamocn, @xlecours, @cmadjar  what do you think?

**Comment by cmadjar** [comment]
See the following document for discussion on how to refactor this: https://docs.google.com/document/d/1secjwOXBjk0G3aOi6-_k2Euszir-vyEwxIIiO2Gb6jg/edit

**Comment by cmadjar** [comment]
Had a meeting with Derek to figure out the best way to design the download button on the frontend. The current design is perfect! There will be just minor modification to be made:

1) when clicking on the download button, have a popup telling the user they are about to download XXX GB of data, do they want to proceed? (to avoid any clicking on mobile devices by mistake)
2) when a dataset is not available for direct download, still display the direct download section but grey out the download button and explain why the dataset is not available for direct download (either too big to be handled by the frontend or a third-party account is required)

**Comment by cmadjar** [comment]
PR with the download button on conp-portal from Xavier: https://github.com/CONP-PCNO/conp-portal/pull/381

PR from Cécile to Xavier's branch to update the download button layout and the portal code to the latest version: https://github.com/xlecours/conp-portal/pull/3

**Comment by xlecours** [comment]
Phase # 1 completed.
**[TL;DR]** The downloadable datasets are compressed and stored locally and made accessible by the web server as static content. There is no automation on cache cleanup or size quotas, the caching mechanism is manual. Neither the backend nor the frontend are involved in the file serving; only the web server. Simple and powerful.
