### ISSUE TITLE
Provide a more user-friendly option for data upload than DataLad

### ISSUE THREAD

**Issue by cmadjar** [CONP-PCNO/conp-portal#284]
## Purpose

From the webinar feedback form:

"Data Upload: I like the idea of Zenodo and OSF and how CONP leverages such available tools for data integration and sharing.
DataLad option seems good at this point, but it requires some steps to set up, and as mentioned in your document, it is only compatible with Linux and Mac machines. That would be great if the better and more user-friendly options will be provided in the future."

**Comment by emmetaobrien** [comment]
It seems to me like providing the Alan button as per https://github.com/CONP-PCNO/conp-portal/issues/283 might plausibly address this issue as well.  How many different ways to download data do we want to support?

**Comment by glatard** [comment]
If this is really about data upload (not download) then I think Zenodo and OSF are the answers. If this is about data download then yes, #283 is the way to go.

**Comment by cmadjar** [comment]
This issue was indeed for easier upload process, not the Alan button.

It looks like the user was happy to have Zenodo and OSF upload process but was hoping for an easier upload process on the DataLad front. Not sure how easy or realistic that is.

@glatard Feel free to close the issue if you think this is not really an issue. I don't have any strong opinion on the matter :).

**Comment by glatard** [comment]
Maybe we should contact the user to know more about it. If you DM me their email address I might be able to find their GitHub handle. As it is, I can't think of an easier way to upload data than uploading to Zenodo or OSF.
