### ISSUE TITLE
Implement a GUI for creating DATS models

### ISSUE THREAD

**Issue by cmadjar** [CONP-PCNO/conp-portal#286]
## Purpose

From the webinar feedback form and in the big item roadmap Github project.

Create a GUI to generate DATS models for the dataset.

Would also be nice to have a clear automated way to generate the DATS model.

**Comment by cmadjar** [comment]
Timeline: aim to have that for July.

@liamocn @emmetaobrien can you guys work together on that to deliver something in July?

**Comment by cmadjar** [comment]
Update from the CONP dev calls on the plan to move forward with the DATS GUI editor.

Discussed in July 2nd:
- The DATS GUI editor needs to be implemented in NeuroHub and Portal so the code should be independent
- Phase 1: editor for the creation of DATS.json file
- Phase 2: ability to add fields etc… so can support other JSON types

Discussed in July 8th:
- Proposed to be a separate repo built entirely with React, as the editor has potential applications in both CONP and Neurohub.
- Phase 1 requirements: user can create a DATS.json file using form fields split up into groups. These fields will be validated using rules specific to the integration platform (i.e. CONP/Neurohub). We already have these for CONP.
- Configurable per integration - validation rules; where the DATS.json actually goes once created; probably others

**Comment by cmadjar** [comment]
@liamocn did a very nice presentation of the tool during the CONP dev of July 29th, 2020 and the following feedback were given:

- Add * next to required fields
- Add example values in the box (email example, etc…)
- Add description of fields when hover over the title of the box
- CONP status should be a drop down
- License field should be a drop down
- Email should be formatted as email format
- Logo can be URL or file path in the dataset repository
- Add \n next to items in the resulting DATS file so it is formatted in a way that is easy to read for humans
- Add capacity to upload already existing DATS file to be able to modify them via the GUI
- Add link to schema definition
- Update the documentation on what to do next once the DATS.json is created and link the documentation to the editor

I had one additional question for you @liamocn where is the code of your DATS GUI? Is there another repository for it? 

Thank you!

**Comment by liamocn** [comment]
@cmadjar  It's in another repository but I haven't pushed it anywhere yet. Can you create a new repository under CONP-PCNO? Once that's up I can add it as the remote and push the code.

**Comment by cmadjar** [comment]
@liamocn I just created a new repository: https://github.com/CONP-PCNO/conp-dats-editor

If you can update the README file when you commit the code, that would be awesome. Thanks!

**Comment by cmadjar** [comment]
@liamocn notes from today's meeting:

- Display what went wrong when cannot download the DATS file (summary + box highlighting)(@liamocn)
- Add tests (@liamocn)
- Need extra pairs of eyes to look at the editor (@emmetaobrien, @cmadjar)
new fields under extraProperties.
- Add the origin extraProperties fields to the editor (see https://github.com/CONP-PCNO/conp-dataset/issues/370, @emmetaobrien and @liamocn to follow up on this)

For later versions:
- Add ability to load any schema, not just CONP schema
- Note that CONP requirements cannot be entirely met from schema because of validation of our own

**Comment by cmadjar** [comment]
Notes from today's meeting:

- @emmetaobrien and @liamocn to finalize the fields in the GUI editor
- Tests being written for the editor
- Make it working with CONP, then standalone so it can be used by CONP and Neurohub, then standalone that could be used by anyone
- @liamocn  to quickly show this off next Wednesday again - maybe also take us through the automated testing as well?

**Comment by cmadjar** [comment]
@liamocn I finally was able to look at the GUI editor. This looks great! 

I took the PREVENT-AD open DATS file to test the GUI and I found a few issues. Below are two checklists of things to correct. I figured it would be easier to track what is done this way.

Here are comments regarding the GUI:
- [ ]  would be good to have a clear layout of why the confirm button does not work: display the error present in the form as a summary of errors to be corrected, instead of having to chase the guilty field.
- [ ] could the downloaded file be called DATS.json instead of dats.json i
- [ ] would be nice a have a "clear" button for people that will create multiple DATS files in a row, instead of having to reload everything
- [ ]  creators role: could there be an empty option? For example, when the creator is a consortium, then it is neither a PI or a collaborator. @emmetaobrien thoughts about this?
- [ ] when email is not filled, it will add to the creators section of the JSON a `"email": ""` will that be an issue for the tests or the portal when reading the DATS file? 
- [ ] for some reason, the type box loses focus after you type one letter making the user having to click again on the type box to enter another letter and so on...
  - [ ] same comment for keyword boxes
  - [ ] same comment for format boxes
  - [ ] same comment for the Date description field
- [ ] Files should probably be labelled as Number of files in the GUI to make it clearer, I know it is in the information but might make it easier for the user. Also, numbers could also be displayed 28,748 instead of 28748 to make it easier to read big numbers.
  - [ ] Same comment for Subjects: could be relabelled Number of subjects
- [ ] Primary publication section is missing a lot of boxes to be complete (see comments on the JSON side as to what it should look like)
  - [ ] same comment for dimensions (see preventad-open DATS.json example)
  - [ ] same comment for acknowledges (see preventad-open DATS.json example)
- [ ] dimensions ask for an array as input, instead, there should be data entry boxes for `name` and `description` and the ability to add more than one dimension
  - [ ] same comment for spatial coverage
- [ ] Source for the DOI is coded 'Zenodo DOI' in DATS files but the GUI expects a URL. Not sure which one is correct. @emmetaobrien?
- [ ] Citations - What is this? Is that the same thing as the primaryPublications that is in page 1 of the GUI @emmetaobrien?
- [ ] Citations must be of array type error when entering a string...
- [ ] Produced by, what is this referring to? Isn't it the same thing as creators in page 1 of the GUI? @emmetaobrien?
- [ ] Is about should allow multiple entries (Alzheimer, Older adults human etc...)
  - [ ] same comment for hasPart I think (@emmetaobrien maybe you can give details about that field to @liamocn?)
- [ ] what is refinement? @emmetaobrien? what should we expect it to be?
- [ ] aggregation: should this be a drop down of values? If so, which ones? @emmetaobrien 
- [ ] identifier fields not automatically populated when loading a JSON with those already entered
- [ ] identifierSource does not need to be a site I think. For PREVENT-AD, it has be labelled `Zenodo DOI`. @emmetaobrien should this have been the zenodo site instead of `Zenodo DOI`?
- [ ] Privacy: the privacy value for preventad-open is "Open Access" but the available options in the GUI are Public, Private and Registered. @emmetaobrien does that mean that we need to change that for both PREVENT-AD datasets?:
- [ ] Spatial Coverage should have a name and a description box. I think it can also have more than one value since it is an array in the JSON file:
```
"spatialCoverage": [
    {
      "name": "Québec (province)",
      "description": "Province of Québec, Canada"
    }
  ],
```
- [ ]  missing the new origin extraProperties fields: (origin institution or origin_consortium is required. See with @emmetaobrien for more information while I am away
```
{
      "category": "origin_consortium",   // or origin_institution
      "values": [
        {
          "value": "PREVENT-AD Research Group"
        }
      ]
    },
    {
      "category": "origin_city",
      "values": [
        {
          "value": "Montreal"
        }
      ]
    },
    {
      "category": "origin_province",
      "values": [
        {
          "value": "Quebec"
        }
      ]
    },
    {
      "category": "origin_country",
      "values": [
        {
          "value": "Canada"
        }
      ]
    }
```

JSON errors noticed: 
- [ ] unit size should be entered as GB instead of gb (or MB instead of mb) in the JSON file
- [ ] primary publication not saved and should look like that in the JSON file:
```
  "primaryPublications": [
    {
    "title": "Rationale and Structure for a new Centre for Studies on Prevention of Alzheimer's Disease (StoP-AD)",
    "publicationVenue": "The Journal of Prevention of Alzheimer's Disease - JPAD Volume 3, Number 4, 2016",
    "authors": [
      {
        "fullName": "John C.S. Breitner",
        "firstName": "John",
        "middleInitial": "C.S.",
        "lastName": "Breitner",
        "affiliations": [
          {
            "name": "PREVENT-AD Research Group"
          }
        ]
      },
      {
        "fullName": "Judes Poirier",
        "lastName": "Poirier",
        "affiliations": [
          {
            "name": "PREVENT-AD Research Group"
          }
        ]
      },
      {
        "fullName": "Pierre E. Etienne",
        "firstName": "Pierre",
        "middleInitial": "E.",
        "lastName": "Etienne",
        "affiliations": [
          {
            "name": "PREVENT-AD Research Group"
          }
        ]
      },
      {
        "fullName": "Jeannie M Leoutsakos",
        "firstName": "Jeannie",
        "middleInitial": "M",
        "lastName": "Leoutsakos",
        "affiliations": [
          {
            "name": "PREVENT-AD Research Group"
          }
        ]
      }
    ],
    "dates": [
      {
        "date": "2016-09-01",
        "type":
          {
            "value": "Publication Date"
          }
      }
    ],
    "identifier": {
      "identifier": "http://dx.doi.org/10.14283/jpad.2016.121",
      "identifierSource": "International DOI Foundation"
    }
  }
],
```

**Comment by cmadjar** [comment]
@liamocn @emmetaobrien can you work together to get these issues resolved for the next CONP dev meeting? Thanks!

**Comment by emmetaobrien** [comment]
@cmadjar : @liamocn and I talked through many of these issues immediately after last Wednesday's meeting, and came up with answers and prioritisation (e.g. `refinement` and `aggregation`, which are in the DATS schema but which we have not as yet used in CONP, I suggested we mask from the interface for our first GUI version.)

**Comment by liamocn** [comment]
@cmadjar This is ready for review again if you could pull the latest code and review your points above. I've checked off the boxes I actioned, some of the others are either fields we removed or there wasn't a clear consensus on them. Thanks!

**Comment by cmadjar** [comment]
@liamocn Thank you for making the changes while I was away. :-)

**New comments on the GUI and the resulting DATS.json:**
- [ ] improvements on the download page (page displayed after clicking on the 'CONFIRM' button)
  - [ ] there should be a button that allows the user to go back to the form if the user wants to edit a field
  - [ ] there should be a button that allows the user to start the creation of a new DATS file. At the moment, the only way to do that is by refreshing the page.
  - [ ] modification of the text displayed to: (Note: there is currently a typo in **and** in addition to the text added)
```
The DATS.json file has been created and should be accessible below or in your downloaded files. If the file was not automatically downloaded, click on the 'DOWNLOAD' button below to download it. 
To edit the current DATS file, click on the 'EDIT' button.
To start the creation of a new DATS.json file, click on 'CREATE A NEW DATS'. 
``` 
- [ ] I wonder if we should not add a timestamp to the filename when a user creates a DATS file so that if they create multiple DATS file, the downloaded file does not overwrite the previous downloads. What do you think?
- [ ] it does not look like the CLEAR button does anything
- [ ] primary publication related comments:
  - [ ] there is a delete cross between 'Add another affiliation' and 'Add another author'. When clicking on it, it deletes the last author. Could that delete cross be located next to the Author Full name instead to make it clearer what it does?
    - [ ] same comment for the delete cross for the publication, could that one be next to the publication title?
  - [ ] it would be helpful if all the subsections for a paper were indented (like the authors, dates, identifiers). Also, the label of those should probably be 'Primary Publication Authors', 'Primary Publication Dates', 'Primary Publication Identifiers' to make it clearer that they are different from the dataset Identifier and Dates fields.
  - [ ] for the primary publication date, the description is not read from the DATS file when loading the PREVENT-AD DATS file (value should have been Publication Date). 
  - [ ] could the button 'Add another affiliation' be located next to the delete cross for the affiliation to make the distinction clearer to the user between the 'Add another author' and 'Add another affiliation'. The additional author is at the paper level while the affiliation is at the author level. 
    - [ ] same comment for the "Add another date" button
- [ ] The box next to the Name in the Acknowledges section should be labelled Abbreviation, not Description
- [ ] The value for creators should be "Principal Investigator" instead of "pi"
- [ ] The date saved in the DATS.json file for the primary publication look like that: `2016-09-02T00:00:00.000Z` but should instead look like `2016-09-02`. 
- [ ] it looks like there is a difference of one day between the displayed date in the GUI and the saved date in the JSON file? Weird...

**Leftovers from previous review:**
- [ ] when email is not filled, it will add to the creators section of the JSON a "email": "" will that be an issue for the tests or the portal when reading the DATS file?
- [ ] creators role: could there be an empty option? For example, when the creator is a consortium, then it is neither a PI or a collaborator. @emmetaobrien thoughts about this?
- [ ] Source for the DOI is coded 'Zenodo DOI' in DATS files but the GUI expects a URL. Not sure which one is correct. @emmetaobrien?
- [ ] Produced by, what is this referring to? Isn't it the same thing as creators in page 1 of the GUI? @emmetaobrien?
- [ ] Is about should allow multiple entries (Alzheimer, Older adults human etc...)
 - [ ] same comment for hasPart I think (@emmetaobrien maybe you can give details about that field to @liamocn?)
- [ ] identifierSource does not need to be a site I think. For PREVENT-AD, it has be labelled Zenodo DOI. @emmetaobrien should this have been the zenodo site instead of Zenodo DOI?
- [ ] Privacy: the privacy value for preventad-open is "Open Access" but the available options in the GUI are Public, Private and Registered. @emmetaobrien does that mean that we need to change that for both PREVENT-AD datasets?:

**Comment by cmadjar** [comment]
@liamocn I love what you did with the primary publication fields!!! This is looking very good.

Below are a few other bugs I noticed (almost there!):
- [ ] when reading an existing DATS file that does not have a `role` for the `creators`, the GUI reads it as `Contributor` instead of `None`
- [ ] the derived from fields do not get populated when uploading a DATS file with derivedFrom field
  - [ ] probably related. After downloading the new DATS file, the derivedFrom fields are not present in the DATS file. Below is the structure of the DerivedFrom in the DATS file under the extraProperties section.
```
  "extraProperties": [
    .............,         #other extraProperties fields
    {
      "category": "derivedFrom",
	  "values": [
        {
          "value": "https://github.com/conpdatasets/preventad-open/tree/17dd9742a89e60f720f8276d79d917c54dd20695"
        }
      ]
    },
    {
      "category": "parent_dataset_id",
	  "values": [
        {
          "value": "preventad-open"
        }
      ]
    }
  ]
```
- [ ] what does the `Accepted files` and `Rejected files` mean in the download page?
- [ ] in the download page, could the "To edit the current...." sentence be on a new line?
  - [ ] same thing for the sentence "To start the creation ..."
- [ ] I do not see an EDIT button as specified in the text in the download page (my guess is that the BACK button is actually the EDIT button and you just need to change the label of the button)

I will also ask @emmetaobrien and @zxenia to test the editor this week to have other feedback than mine :). Thank you!

**Comment by cmadjar** [comment]
@liamocn Thank you for the quick updates!

I ran the DATS file obtained with the latest version of the dats_validator.py and I got the following error:
```
1 Validation error in PREVENT-AD open data in BIDS format: extraProperties.category.CONP_status - conp is not allowed value for CONP_status. Allowed values are ['CONP', 'Canadian', 'external'].
```
So the encoding of the CONP_status field values needs to be corrected to use those values.

Thank you!

**Comment by liamocn** [comment]
@cmadjar That's corrected now, and I can see it's passing the validator on my end. Can you pull the latest and try again?

**Comment by cmadjar** [comment]
@liamocn This is passing the validator too on my end 🥇 . This is AWESOME!!

@emmetaobrien and @zxenia will also test it this week or early next week. 

In the meantime, I think it is in a pretty good shape already and ready to be pulled on the portal. @liamocn Could start working on integrating the GUI on the portal in a PR to conp-portal?

Thank you!

**Comment by zxenia** [comment]
Hi @liamocn 
I started testing the editor (latest master version) and it seems like something goes worng:

1. When I upload DATS.json I get the following error (tested with 4 different valid DATS files):

![bug](https://user-images.githubusercontent.com/11253950/93898916-c576b400-fcc1-11ea-8c53-92dc803b59ad.PNG)


2. When I try to create a DATS file from scratch, I am able to get to the Extra properties part. When I set Access - Landing Page there is a strange UI behavior - the UI disappears (white screen). If I don't set Landing Page and hit CONFIRM the UI disappears again.


I went through @cmadjar feedback and seems like all of these things were working before, so my guess that something happened with the latest commits.

Tests pass except for a few console errors.

**Comment by liamocn** [comment]
Hi @zxenia, Thanks for the feedback! I think I see the issue that was throwing up the 'values' error, I'll see if I can reproduce it. For the other issue (the strange UI behaviour), can you see anything in your browser's console when the white screen occurs? You can usually open the console (Chrome and Firefox) with Ctrl-Shift-I on Windows.

**Comment by zxenia** [comment]
Hi,
yes, it has an error like this:

```
Uncaught Error: Objects are not valid as a React child (found: object with keys {landingPage}). If you meant to render a collection of children, use an array instead.
    in h6 (created by ForwardRef(Typography))
    in ForwardRef(Typography) (created by WithStyles(ForwardRef(Typography)))
    in WithStyles(ForwardRef(Typography)) (created by Formik)
    in div (created by Formik)
    in form (created by Form)
    in Form (created by Formik)
    in Formik (created by DatsEditorForm)
    in div (created by ForwardRef(Paper))
    in ForwardRef(Paper) (created by WithStyles(ForwardRef(Paper)))
    in WithStyles(ForwardRef(Paper)) (created by DatsEditorForm)
    in div (created by DatsEditorForm)
    in DatsEditorForm (at App.js:6)
    in App (at src/index.js:7)
```
