### ISSUE TITLE
Create DATS model validator with the required fields

### ISSUE THREAD

**Issue by cmadjar** [CONP-PCNO/conp-portal#287]
## Purpose

This was in the big roadmap items project https://github.com/CONP-PCNO/conp-portal/projects/2.

Create a DATS model validator that will check the required fields in the DATS file.

**Comment by cmadjar** [comment]
@emmetaobrien do you know if this is something that exists or under development?

**Comment by emmetaobrien** [comment]
https://github.com/emmetaobrien/dats-validator/blob/master/perlscripts/1000genomes_validate_json.pl - which is not specific to the 1000 Genomes dataset, I should rename it - can check any DATS.json against a local copy of the relevant schema.  

I believe there may have been some issues with indicating in a schema that a field under `extraProperties` was required, though, so I am not sure this is a complete solution; @PapillonMcGill has done most of the work on modifying the schema so might be able to give a more definitive answer.  Also this does not validate JSON-ld components and may raise errors with a DATS file containing them.

**Comment by PapillonMcGill** [comment]
@emmetaobrien That validator is not 100% correct. datagsuite have one available that do validate 100%
https://github.com/datatagsuite/dats-tools

**Comment by emmetaobrien** [comment]
If that works to validate our added fields under `extraProperties`, excellent.

**Comment by joeyzhou98** [comment]
@emmetaobrien I believe this is already implemented in CircleCI and @mathdugre is maintaining and developing all the testing and validating of DATS

**Comment by emmetaobrien** [comment]
If this is already implemented in CircleCI that would be great.  My understanding is that @mathdugre's time with this project finished at the end of May, yes?

**Comment by joeyzhou98** [comment]
Yes that is correct

**Comment by emmetaobrien** [comment]
So who is currently maintaining the test suite ?

**Comment by joeyzhou98** [comment]
I will be maintaining it in the meantime, but I am not familiar with CircleCI so changes will take time for me to implement/fix

**Comment by emmetaobrien** [comment]
Right. One thing that would be useful at some point is if you could confirm that we are validating the required fields under `extraProperties` as I mentioned above; my notes indicate that we had difficulty with that at some point but I am unclear as to whether that was solved.

**Comment by joeyzhou98** [comment]
The DATS validator in CircleCI checks for if `extraProperties` is an array according to [here](https://github.com/CONP-PCNO/schema/blob/29134fd4aa16f7e76b6b9e20238c7b4de82b8518/dataset_schema.json#L198). It also checks for other fields inside `extraProperties` according to [this](https://github.com/CONP-PCNO/schema/blob/29134fd4aa16f7e76b6b9e20238c7b4de82b8518/category_values_pair_schema.json) and this goes on until everything is verified to fit the relevant schemas

**Comment by emmetaobrien** [comment]
@joeyzhou98: that is checking that entries under `extraProperties` are correctly formatted, but it is not, if I understand it correctly, confirming the existence of specific entries under `extraProperties` which are required in our specification (https://github.com/CONP-PCNO/conp-documentation/blob/master/CONP_DATS_fields.md), at the moment `extraProperties->files` and `extraProperties->subjects`.  If this can be done by further modifying the schema, great, but if not, we need some other means to do this validation at the time of submission.  

The same probably applies to the fields we are making required under `distributions` - is there, for example, a way to modify the DATS schema to confirm that `distributions->access->authorizations` exists and contains one of the values "public", "registered" or "private" ?

**Comment by glatard** [comment]
just in case it was ambiguous: the tests use function `validate` from `scripts/dats_validator/validator.py`, which validates the DATS model against our schema available here: https://github.com/CONP-PCNO/schema/tree/29134fd4aa16f7e76b6b9e20238c7b4de82b8518 Do we need anything more than that?

**Comment by cmadjar** [comment]
@emmetaobrien if I understood correctly what was said during the call today, all the required fields are being validated by the DATS validator now, correct? If so, should we close this issue?

Note: the validation of extraProperties will be logged in a separate ticket that already exists: https://github.com/CONP-PCNO/conp-dataset/issues/345

**Comment by emmetaobrien** [comment]
All the required fields outside `extraProperties` are currently being validated by the DATS validator, so yes, this issue should be closed.
