### ISSUE TITLE
Remove empty source link in dataset page

### ISSUE THREAD

**Issue by glatard** [CONP-PCNO/conp-portal#289]
When the source URL of the dataset is not present, it should be omitted from the dataset page rather than showing as "None" as is the case in the dataset below:

![Screenshot from 2020-05-22 13-08-13](https://user-images.githubusercontent.com/5174953/82692221-50b93d80-9c2d-11ea-8d27-8cc5948cc2a1.png)

## Expected Behavior
Don't show a source link if there is none to display, just remove the line in the GUI instead.

## Current Behavior
A broken "None" link shows.

**Comment by cmadjar** [comment]
It looks like this has been fixed as I don't see that behaviour anymore on the portal so closing the issue.

https://portal.conp.ca/dataset?id=projects/Reusing-Neuro-Data
