### ISSUE TITLE
fatal: unknown refname: format strip=2

### ISSUE THREAD

**Issue by tashrifbillah** [CONP-PCNO/conp-portal#318]
Installed datalad with Python 3, version 0.12.7

```bash
(base) [tb571@pnl-z840-2 tmp]$ datalad install https://github.com/CONP-PCNO/conp-dataset.git

CommandError: command '['git', 'for-each-ref', '--format=%(refname:strip=2)', 'refs/heads', 'refs/remotes']' failed with exitcode 128
Failed to run ['git', 'for-each-ref', '--format=%(refname:strip=2)', 'refs/heads', 'refs/remotes'] under '/tmp/conp-dataset'. Exit code=128. out= err=fatal: unknown refname: format strip=2

fatal: unknown refname: format strip=2
```

**Comment by yarikoptic** [comment]
yikes. it is datalad/git issue.  what version of git is that? `git --version`

**Comment by emmetaobrien** [comment]
Have you got` git `and `git-annex` installed ? Our current setup requires `git-annex` version >= 8.20200309,

**Comment by tashrifbillah** [comment]
I see two opposing comments-- is `git-annex` required by CONP?

```bash
(base) [tb571@pnl-z840-2 tmp]$ git --version
git version 1.8.3.1
```

**Comment by emmetaobrien** [comment]
Both git and git-annex are requirements for using Datalad with CONP.

**Comment by yarikoptic** [comment]
Now there is datalad side issue: https://github.com/datalad/datalad/issues/4636  which we will address by stating minimal supported/needed version of `git`.  @tashrifbillah - please look into upgrading `git` from a version released in 2013. `conda` might be the easiest way forward: https://anaconda.org/anaconda/git

**Comment by ltetrel** [comment]
To install git annex (before datalad):
```
sudo apt-get update
# install git-annex-standalone https://git-annex.branchable.com/install/
# following informations from http://neuro.debian.net/  
wget -O- http://neuro.debian.net/lists/stretch.us-nh.full | sudo tee /etc/apt/sources.list /neurodebian.sources.list
# https://github.com/jacobalberty/unifi-docker/issues/64
sudo apt-key adv --recv-keys --keyserver hkp://ipv4.pool.sks-keyservers.net:80 0xA5D32F012649A5A9
sudo apt-get update
sudo apt-get install git-annex-standalone
```

**Comment by tashrifbillah** [comment]
Thanks @ltetrel, I'll find a way to get it installed on RHEL. Your instruction is Ubuntu :)

**Comment by ltetrel** [comment]
Sorry, did not read carefully!

**Comment by tashrifbillah** [comment]
Sorry, installation of `git-annex` didn't remedy the problem :(

**Comment by tashrifbillah** [comment]
```bash
(base) [tb571@pnl-z840-2 ~]$ git annex version
git-annex version: 5.20140221
build flags: Assistant Inotify DBus Quvi TDFA
key/value backends: SHA256E SHA1E SHA512E SHA224E SHA384E SHA256 SHA1 SHA512 SHA224 SHA384 WORM URL
remote types: git gcrypt bup directory rsync web tahoe glacier hook external

```

**Comment by emmetaobrien** [comment]
The current CONP setup requires git-annex version >= 8.20200309.

**Comment by tashrifbillah** [comment]
I see, the `yum install` pulled a very old one.

**Comment by glatard** [comment]
Hi @tashrifbillah see the install instructions for RHEL here: http://handbook.datalad.org/en/latest/intro/installation.html#install

**Comment by cmadjar** [comment]
@tashrifbillah I just wanted to follow up on this. Were you able to install the required version of DataLad and git-annex and get the data you were looking for? Thanks.

**Comment by yarikoptic** [comment]
and FWIW, as I stated above -- initial issue is not about the elderly version of `git-annex` per se -- it is about "ancient" version of git.  It is git to be upgraded, not git annex.  Or if you install a "standalone" build of git-annex -- it will come with git included and datalad should use that "bundled" version by default (if it is detected to reside along git-annex)
