### ISSUE TITLE
The search box works poorly

### ISSUE THREAD

**Issue by prioux** [CONP-PCNO/conp-portal#334]
The search box in the dataset section doesn't seem to search everything.

If I type 'openneuro', it doesn't find the visual working memory dataset even though the logo and the url contain that keyword.

If I type 'evans', I only get three results, none of them being e.g, datasets that are associated with the PI Alan Evans, like the single subject phantom dataset.

**Comment by glatard** [comment]
This is related to #183. @cmadjar, I think we should have this issue prioritized.

**Comment by cmadjar** [comment]
@glatard thanks for linking the issues! I will prioritize this.

Sorry for the delay, just came back from vacation...

**Comment by cmadjar** [comment]
@prioux this appears to have been fixed now. I tried filtering for `evans` and `openneuro` on the updated portal and I do get the results you mentioned in the issue now. 

Thank you for reporting that!
