### ISSUE TITLE
Display issue with Safari on iPhone

### ISSUE THREAD

**Issue by emmetaobrien** [CONP-PCNO/conp-portal#339]
I have had feedback describing a display issue with the data list page in Safari on iPhone 11 Pro Max; the appearance of the page is ![garbled](https://github.com/emmetaobrien/conp-misc/blob/master/IMG_4039.jpg?raw=true).

**Comment by liamocn** [comment]
@emmetaobrien Thanks for this, I've just sent a PR which improves how the navigation bar and dataset pages render on smaller screens. Can you or @cmadjar take a look when you can?
