### ISSUE TITLE
Run CONP pipelines in CBRAIN

### ISSUE THREAD

**Issue by cmadjar** [CONP-PCNO/conp-portal#347]
## Tasks

1) Make sure that all CONP pipelines that are available in CBRAIN appear as such in the CONP portal.
2) When user click on the CBRAIN button in a CONP pipeline, redirect to the pipeline launch page instead of the generic CBRAIN login.

## How

Point 2 most likely requires storing a CBRAIN tool config id for each pipeline, preferably as a config file also available on GitHub for easier update. This design would also solve point 1, as a pipeline will be assumed to be installed in CBRAIN if and only if it has a valid tool config id. When registering config ids, one should make sure that they match the exact same pipeline (boutiques descriptor) than registered in CONP.

## Who

CONP developers (@cmadjar, @mandana-mazaheri), liaise with  @nbeck to get tool config ids.

## Related issues 

#63

**Comment by cmadjar** [comment]
For 2. there might be difficulties within CBRAIN to access directly the tool form as users have to first select data in order to see the form.  @natacha-beck will investigate if possible to change that in CBRAIN.

**Comment by natacha-beck** [comment]
As mentinonned it is not possible to get directly the tool form. 

What should be possible is to get something like that: 

<img width="1399" alt="Screen Shot 2020-10-09 at 1 59 37 PM" src="https://user-images.githubusercontent.com/777590/95616579-00097c00-0a38-11eb-8905-6582e1d22a4e.png">

But it is some javascript event, I need to see how we can get the same behaviour with a link.

**Comment by natacha-beck** [comment]
@liamocn and @glatard This [PR](https://github.com/aces/cbrain/pull/1047) in CBRAIN will allow you to do that. If you want to prepare a specific tool you need to know the `id` of the tool. Once you know it the link you should have on CONP will be like the following `https://portal.cbrain.mcgill.ca/userfiles?prepare_tool_id=XX` (XX == tool_id).

**Comment by cmadjar** [comment]
I believe this is done. I can click on the CBRAIN logo and it redirects me to the tool ID in CBRAIN. 
 @mandana-mazaheri can you confirm? If you confirm, can you close the issue? Thank you!

**Comment by mandana-mazaheri** [comment]
Thanks Cecile,

Yes I confirm, I will close the issue.

Best regards
Mandana
