### ISSUE TITLE
Process CONP datasets in CBRAIN

### ISSUE THREAD

**Issue by cmadjar** [CONP-PCNO/conp-portal#348]
## Task

- Create a CBRAIN data provider for the whole CONP dataset, access datasets on this data provider or create a CBRAIN data provider for each CONP dataset.
- Store a CBRAIN data provider id for each dataset.
- In each dataset page, add a link to redirect to the CBRAIN dataset page in the CBRAIN portal.

## How

The ideal solution would be to use CBRAIN's DataLad data provider. Otherwise, install and download the datasets on a server (suggestion: Beluga, to facilitate processing), and register this location as a regular CBRAIN data provider. Make sure that simple pipelines (Diagnostics) can be run on the files. In any case, new datasets should be created automatically (either create a new data provider or register new files to an existing data provider).

The CBRAIN data provider id should be stored using a mechanism similar to the one used to store CBRAIN tool config ids (see previous point). Suggestion: JSON file available in the portal config on GitHub.

## Who

This is on the CBRAIN roadmap. Need to make sure that the CBRAIN DataLad provider works as expected.
Liaise with CONP developers for DataLad expertise.

## Notes

Something specific has to be done for datasets that require authentication. The CBRAIN team will manually configure permissions.

## Related issues 

#63

**Comment by jbpoline** [comment]
I think this requries a discussion with NeuroHub as well

**Comment by glatard** [comment]
Following discussion with @prioux and Bryan at the CONP meeting today:

CONP datasets are exposed as CBRAIN projects. The internal mapping to data providers is CBRAIN's business, not CONP's.

Remaining actions on this issue:
- for each CONP dataset available in CBRAIN, add a "CBRAIN" button to the data set page
- this button redirects to the corresponding project page in CBRAIN, where users can launch pipelines on the files in this dataset

Additional datasets will be added by the CBRAIN team.

**Comment by cmadjar** [comment]
@mandana-mazaheri here is a summary of our meeting with Derek with the design proposal we discussed.

Modify a little the design of the card to have 4 columns instead of three:
1. the column with the dataset logo, canadian flag and number of views (nothing to be changed in that column)
2. the column with the dataset title, summary description and source link (will remove the "Browse on Github" link from that column as it will be in the third column
3. a column with a BROWSE title with the GitHub logo and the CBRAIN button (each pointing to a link to GitHub or CBRAIN dataset page respectively). Grey out the CBRAIN button when the dataset is not on CBRAIN but keep it there.
4. the DOWNLOAD column with the two action buttons labelled Metadata and Dataset

Example of what a card would look like with this new design:
![Screen Shot 2021-04-06 at 4 29 40 PM](https://user-images.githubusercontent.com/1402456/113774885-dfc02e80-96f5-11eb-9265-1d9560d8ecb2.png)

**Comment by mandana-mazaheri** [comment]
Thank you so much Cecile

**Comment by cmadjar** [comment]
@mandana-mazaheri following today's meeting, here is what the card would look like with the addition of the CBRAIN button. The rest of what has been discussed can be a different issue tackled by someone else. One task at a time :)

![Screen Shot 2021-04-07 at 10 32 23 AM](https://user-images.githubusercontent.com/1402456/113884466-fd8ca280-978c-11eb-8fb6-55800be655ab.png)

**Comment by mandana-mazaheri** [comment]
Great, thanks Cecile
