### ISSUE TITLE
Format errors/issues observed in DATS.json files generated by GUI.

### ISSUE THREAD

**Issue by emmetaobrien** [CONP-PCNO/conp-portal#358]
Problems  observed while @srmemar and I were generating` DATS.json` files for the MouseBytes dataset.

The following were observed in two versions of the file:

- Dates saved as `yyyy-mm-dd` when the validator expects  `yyyy-mm-dd hh:mm:ss`.
 
- Dates saved with an invalid subfield `dates->description`, the contents of which should be in `dates->types->value`
 
- `distributions->size` saved as a string when the validator expects a number
 
- invalid empty value for `acknowledges->funders`

Also, in the version of `DATS.json` updated for a second subdataset, a comma was missing before `hasPart` which initially caused the file to fail validation.

While it does not cause problems with the validator, the GUI currently saves an empty value for `extraProperties->parent_dataset_id` for a non-derived dataset, which is inconsistent with our standards, it would be better to my mind if that property was only stored for derived datasets.

These issues have been manually corrected in the MouseBytes dataset so that it would pass validation.

**Comment by cmadjar** [comment]
@liamocn could you fix those issues? Let me know if you need a tester once you send the PR to the DATS GUI editor. Thanks!

**Comment by liamocn** [comment]
Are we sure we want timestamps on the dates? Looking at the PreventAD dataset, there are not timestamps for the dates

`  "dates": [
    {
      "date": "2019-04-30",
      "type": {
        "value": "Release Date"
      }
    },
    ...`

What would be an appropriate timestamp, 00:00:00?

The other issues seem to be small enough and shouldn't take too long to work through.

**Comment by emmetaobrien** [comment]
00:00:00 seems a good default to me; some of the datasets I have set up have more precise timestamps.
