### ISSUE TITLE
Sidebar dashboard button occludes navbar

### ISSUE THREAD

**Issue by tkkuehn** [CONP-PCNO/conp-portal#368]
## Expected Behavior

After scrolling down on any page in the portal, when the "Dashboard" button on the sidebar is highlighted, the highlight should be contained to the sidebar and not spill out onto the navbar.

## Current Behavior

After scrolling down on any page in the portal, when the "Dashboard" button on the sidebar is highlighted, the lighter grey highlight spills onto the navbar.

![Screenshot from 2020-11-12 11-24-47](https://user-images.githubusercontent.com/6700252/98979525-73942280-24e9-11eb-8752-aff09dc614ec.png)

## Environment (optional)

Firefox 82.0.3 on Arch Linux, in a fullscreen window on a 1080p monitor. I can also reproduce it on Chromium 86.0.4240.198.

## Context (optional)

This is not all that important, but makes the UI look kind of odd.

**Comment by cmadjar** [comment]
@liamocn could you look into this? Thank you!

**Comment by cmadjar** [comment]
All fixed. Thank you @liamocn :-)
