### ISSUE TITLE
Open CBRAIN in new tab

### ISSUE THREAD

**Issue by mandana-mazaheri** [CONP-PCNO/conp-portal#400]
## Purpose

To open a new tab for CBRAIN website when clicking on the CBRAIN button to run a pipeline.
## Related issues (optional)
#347

**Comment by cmadjar** [comment]
@mandana-mazaheri have you had a chance to look at this? I know you have been quite busy so no worries if not. Just wanted to follow up on it.

**Comment by mandana-mazaheri** [comment]
Hi Cecile,

Thanks for your understanding, the modifications in the source code are
applied, however there are some issues in the tests, specifically with the
browser.
I'm trying to solve it as soon as possible and do pull request for both
#400 and #401.

Best regards,
Mandana
