### ISSUE TITLE
A block list for pipelines to be hidden in the portal

### ISSUE THREAD

**Issue by mandana-mazaheri** [CONP-PCNO/conp-portal#401]
There are some duplicated pipelines that should be removed from the portal.
## Possible Implementation (optional)

Creating a block list and add any pipeline which should be hidden in the portal

**Comment by mandana-mazaheri** [comment]
Dear @cmadjar I appreciate it if you assign this issue and #400 to me. The deadline can be the end of February for both of them.

**Comment by cmadjar** [comment]
Thank you @mandana-mazaheri . I assigned the issues to you and added them to the roadmap for end of February :-)

**Comment by mandana-mazaheri** [comment]
Hi Cecile,

Thanks for following it up. It is done now, I didn't pull request for this
one since I'm going to do one pull request for this issue and #400 at the
same time.

Best regards,
Mandana
