### ISSUE TITLE
Add prepopulated queries to the Nexus search

### ISSUE THREAD

**Issue by cmadjar** [CONP-PCNO/conp-portal#412]
## Purpose

Create and prepopulate a few Nexus queries in the Advance search page so that users can see examples of Nexus queries or simply use prepopulated queries.

## Related issues 

A follow up to the work that has been done in #276 and #377

**Comment by cmadjar** [comment]
@zxenia feel free to add more notes relevant to this issue. Thanks!

**Comment by cmadjar** [comment]
@zxenia any updates on this? I forgot. If you could update the issue to keep track on where things are at, that would be awesome. Thank you!

**Comment by zxenia** [comment]
Hi @cmadjar, it's coming along.
Sebastian created some nice queries, we planned to use them.
Meanwhile, I started to look into how to add it to the widget I used for sparql editor.
