### ISSUE TITLE
[500 error] for McGill EMC: RNA-seq experiment from human brain sample

### ISSUE THREAD

**Issue by mathdugre** [CONP-PCNO/conp-portal#418]
## Summary
I was browsing through the portal and noticed that there is currently (Mar. 09 12:36) a **500 error** for the *McGill EMC: RNA-seq experiment from human brain sample* dataset.
I'm not sure if this error is transient or persistent, but I thought it would be good to report it here.

https://portal.conp.ca/dataset?id=projects/mcgill-emc-rna-seq-experiment

**Comment by cmadjar** [comment]
@mathdugre thank you for logging the bug. The PR to fix that issue has been sent on conp-portal (#426)
