### ISSUE TITLE
Fix Mobile Layouts

### ISSUE THREAD

**Issue by stronics** [CONP-PCNO/conp-portal#45]
It breaks for NeuroLibre icon, download buttons, and data search aspects. Need to show cards instead

**Comment by paiva** [comment]
NeuroLibre icon fixed, still missing fix for:
1) Dashboard big buttons
2) Search page
3) Nabvar Toogle  on search

**Comment by cmadjar** [comment]
Just looked at the portal on my iPad. Seems fine so I will close this issue as it is probably outdated.
