### ISSUE TITLE
"Process" and "Download" sections of dataset cards overlap at some widths

### ISSUE THREAD

**Issue by tkkuehn** [CONP-PCNO/conp-portal#468]
## Expected Behavior

All columns of the dataset cards should remain legible at all window widths.

## Current Behavior

On both the dataset search page and individual dataset pages, when the browser window is narrow enough to compress the dataset cards, but not narrow enough to push the "Process" and "Download" sections below the summary information, those sections overlap. See the included screenshot.

![Screenshot from 2021-05-26 10-02-57](https://user-images.githubusercontent.com/6700252/119674893-94c7bb00-be0a-11eb-9ff9-6132e003607d.png)

## Environment (optional)

I can reproduce this on Firefox and Chromium on Arch Linux.

## Context (optional)

This doesn't prevent the portal from being used and doesn't have to be high priority, it just looks weird under these circumstances.

**Comment by cmadjar** [comment]
Thank you @tkkuehn  for reporting this! This should be taken care of by PR #465.
