### ISSUE TITLE
Update Nexus data

### ISSUE THREAD

**Issue by zxenia** [CONP-PCNO/conp-portal#484]
## Purpose
The data in Nexus needs to be updated since the context mapping to schema.org was improved.
Also currently there is possible data duplication in Nexus for PREVENT-AD registered data dataset - it needs to be investigated.

Ideally, this update will also include migration to proper dataset identifiers: instead of UUID to a stable identifier from the CONP database. This improvement will allow being redirected from Nexus search results to an individual dataset page. Currently, Nexus results contain dataset resolvable ids that redirect to Nexus dataset representation in JSON.

**Comment by surchs** [comment]
@zxenia what's the desired format for the CONP database URIs for datasets? 

At the moment I can see portal datasets have a URI of the form:
`https://portal.conp.ca/dataset?id=projects/PERFORM_Dataset__one_control_subject`

How are these generated (e.g. when we have new data come in), and do we want to use this form as the resource ID? Something like just 
`https://portal.conp.ca/dataset/PERFORM_Dataset__one_control_subject`
might be cleaner, but I am not sure if there is a reason not to adopt this.

Adopting these dataset based resource IDs is going to be helpful also for updating the existing records in nexus when we make changes to the meta-data on our end - that is, as opposed to just deprecating the original version and creating a new record. So it would help to make sure that we also have an easy way of tying the resource ID / URI unambiguously to a given dataset in the future.

**Comment by zxenia** [comment]
Hi @surchs 

I think we will need to stick with this URIs `https://portal.conp.ca/dataset?id=projects/PERFORM_Dataset__one_control_subject`
because it's how the conp portal route for a single dataset is designed. If we have those URIs in Nexus then the search results will be immediately resolvable to a dataset's detail page.
To have this `https://portal.conp.ca/dataset/PERFORM_Dataset__one_control_subject` will probably require changes to url path.
And if we change them then we have to make the old urls resolvable to those new ones.

> How are these generated

First, I thought that a dataset's database id (or path)  is generated from its title and prefixes with `projects/` - the title is being split by words and added dashes or underscores.
But I cross-checked and I see that it's not true and seems like it's arbitrary looking at the below examples:

```
title: BigBrain dataset - 3D Classified Volumes (derived dataset)
url: /dataset?id=projects/BigBrain_3DClassifiedVolumes

title: Multicenter Single Subject Human MRI Phantom
url: /dataset?id=projects/multicenter-phantom
```

@cmadjar Do you know how a dataset's id is generated in the database?

**Comment by cmadjar** [comment]
@zxenia I think the dataset ID is taken from the submodule name of the dataset you can find in the `.gitmodules` file of the conp-dataset repo (see the example of the ID of `bigbrain-datalad`: this is the name of the git submodule in `.gitmodules` but the folder name under `projects` is `BigBrain`.

**Comment by zxenia** [comment]
@cmadjar ok got it now, thank you!

**Comment by zxenia** [comment]
@surchs Thanks! Yes, it would be good to discuss the IDs issue on a call.  I think we need to look into this soft delete option, but if it requires too much maintenance then adding the attribute in DATS that holds the URL is a good option too.

**Comment by zxenia** [comment]
At the dev call, the decision was made to go with option 1. Once it's done and the data is updated in Nexus, I will need to adjust example SPARQL queries in order to return a conp portal resolvable URL for each dataset.

**Comment by surchs** [comment]
Just to update here: I had checked in with Adeel and the Nexus portal remains unaccessible. He'll let me know once that changes and I'll update here.

**Comment by cmadjar** [comment]
Thank you for the update :)

**Comment by surchs** [comment]
Hey, good news. Adeel let me know that Nexus is up again. I'll have a chat with him regarding our updated `conp_url` attribute and make sure the canned queries are running well.

**Comment by surchs** [comment]
I met with Adeel, checked the ingested data, and changed the canned queries (see linked PR). This should take care of this issue.

**Comment by cmadjar** [comment]
@surchs I guess this could be closed now that the PR is merged, correct?

**Comment by surchs** [comment]
Yes @cmadjar, this is now also taken care of!
