### ISSUE TITLE
[Authentication] Detailed Registration Steps

### ISSUE THREAD

**Issue by paiva** [CONP-PCNO/conp-portal#49]
Need to add the multi-layer registration steps: including agreeing to the ToS, community agreement/expectations, code of conduct, etc.

**Comment by shots47s** [comment]
So a concrete question on how we want this to proceed:

Options:

1. We have a CONP Portal account, and a user needs to register first for that unique account and then we allow them to associate other accounts (e.g. ORCID, but not exclusive) to their account.
   a. Advantages
      1. A unique CONP id
      2. no additional registration required by external systems
      3. have the ability to associate other platform accounts.
   b. Disadvantages
      1. User have to sign up for another account

2. We use ORCID as the CONP user portal account, a user needs to register a valid ORCID first and that becomes your primary login without a separate CONP login.
   a. Advantages
     1. If you have ORCID, no additional steps
     2. Portal not handling any authentication, all shipped to OAUTH
     3. Could still associate with other accounts
   b. Disadvantages
     1. Require our users to go to an external sight to get their initial CONP ID if they don't have one.

Each of these are straight forward.  Right now, the system uses something in between.  I am exploring flask libraries that allow us to mix and match.

**Comment by shots47s** [comment]
Helpful discussion from Flask-Dance, which is a tool for associating accounts to Flask Users through OAUTH, to give you some idea of the technical aspects.

https://flask-dance.readthedocs.io/en/latest/multi-user.html

**Comment by glatard** [comment]
Ultimately I think we want to support both: either login with your preferred website (Orcid, GitHub, etc), or create an account manually. In practice, as dev resources are limited, I would say let's go for Orcid-only in the first release (so option 2), and then see if there's a need for more. That's also what OpenNeuro does (Orcid or Google in their case -- https://openneuro.org/).

**Comment by shots47s** [comment]
Using the proper tools, it is really not much effort to implement one or the other.

Flask-Dance has canned interfaces to many of these (although oddly not to ORCID :))

**Comment by tomgee** [comment]
I agree with Tristan's comment.

**Comment by cmadjar** [comment]
To be discussed when discussing authentication in a different call.
