### ISSUE TITLE
Tools & Pipelines Key Points

### ISSUE THREAD

**Issue by cesare-spinoso** [CONP-PCNO/conp-portal#51]
Overview of the search engine:
Search through tools by using the bosh command line (form Boutiques). Boutiques should act as an "app store" framework where it retrieves tools through bosh search. The unique tool identifier (DOI) is returned from Zenodo and can be used to allow the user to download the tool.
 
One key element about the search is that it should use web caching, as individual bosh searches are quite slow.

**Comment by glatard** [comment]
Hi @cesare-spinoso, that's a good start!

More specifically, I think the caching should work as follows:
1. Search requests should search in `~/.cache/boutiques/*.json`, not through `bosh search` directly.
2. `~/.cache/boutiques/*.json` should be updated regularly, through calls to `bosh pull`.
Step 2 should be implemented through Boutiques' Python API.

We should also precise what will be presented in the portal:
* tool id, tool name, description, link to CBRAIN if available
* output of `bosh pprint` on request (maybe behind a `more` button)
There should also be instructions on how to run the tool, locally or in CBRAIN.

**Comment by glatard** [comment]
The goal here is to implement pipeline search in the following panel of the portal:

![Screenshot from 2019-05-22 20-43-07](https://user-images.githubusercontent.com/5174953/58217771-41c64500-7cd2-11e9-8635-2c2acab1e981.png)

Users should be able to:
* Search pipelines available on Boutiques (similar to `bosh search`)
* Get basic information about the tool (similar to `bosh pprint`)
* Get instructions to run pipelines locally
* Open a pipeline launch form in CBRAIN if pipeline is installed in CBRAIN

A PR has already been open for the frontend, see https://github.com/CONP-PCNO/conp-portal/pull/29 . This code should be reviewed and extended wherever necessary.

For the backend, the search mechanism should work through a caching of Boutiques descriptors on the portal, see description in the previous post. 

@paiva @jbpoline please comment as you see fit.

@joeyzhou98 let us know if anything is unclear!

**Comment by glatard** [comment]
Addressed by #55
