### ISSUE TITLE
Pipeline UI improvements

### ISSUE THREAD

**Issue by glatard** [CONP-PCNO/conp-portal#57]
As discussed with @paiva and @joeyzhou98, #51 will result in a minimal, usable interface for pipeline search. That minimal version should be extended to comply to the mockup initially designed. @joeyzhou98 could add more information following our discussion.

**Comment by shots47s** [comment]
Need cosmetic work to accomplish this.  The names coming from Zenodo are not so good :) . Also need to make sure that all boutique descriptors in Zenodo that run on CBRAIN are labelled to do so.
