### ISSUE TITLE
Porting pipelines to CBRAIN

### ISSUE THREAD

**Issue by glatard** [CONP-PCNO/conp-portal#58]
Tools found through the portal will be identified as available in CBRAIN when their `online-platform-urls` property (a list) contains a URL with the string "cbrain" in it. Many pipelines returned by search aren't currently available in CBRAIN, and if they are, it's likely that their descriptor doesn't include the URL of a CBRAIN portal. Pipelines returned by `bosh search` should be reviewed, added to CBRAIN plugins whenever relevant, and republished.

@shots47s

**Comment by cmadjar** [comment]
Feels to me that this issue should be closed as well. @glatard feel free to reopen it if I am wrong.
