### ISSUE TITLE
versioned Terms of Use

### ISSUE THREAD

**Issue by christinerogers** [CONP-PCNO/conp-portal#602]
If possible, commit a versioned file of the Terms of Use that could be a) downloaded, and b) referenced as a document by EEGNet which will re-use these. 

Currently, EEGNet can refer only to a [line in base_main.html](https://github.com/CONP-PCNO/conp-portal/blob/cd9ed0cee5002e7007e7ccfeda21f17af121493b/app/templates/common/base_main.html#L101) or the [latest commit/branch](https://github.com/CONP-PCNO/conp-portal/pull/478) to reference the CONP terms of use. 

https://github.com/CONP-PCNO/conp-portal/blob/cd9ed0cee5002e7007e7ccfeda21f17af121493b/app/templates/common/base_main.html#L101

**Comment by christinerogers** [comment]
@iremkatitas could you update this issue with a link to the PR / zenodo URL which is helping resolve it? 
Thanks cc @GHPBZ

**Comment by GHPBZ** [comment]
Checked in Terms of Use as a Markdown file (https://github.com/CONP-PCNO/conp-documentation/blob/master/CONP_Portal_Terms_of_Use.md) because it was formerly only in HTML header.  It is also published on Zenodo (https://doi.org/10.5281/zenodo.10023096).
