### ISSUE TITLE
Add link to online platform where pipeline is installed

### ISSUE THREAD

**Issue by glatard** [CONP-PCNO/conp-portal#66]
## Purpose

Pipeline objects have an `online-platform-urls` list property that refers to Web platforms where the pipeline is installed. When this property is defined, pipeline search should add an icon linking to a platform in `online-platform-urls` in the pipeline record.
* When the linked URL contains string "cbrain", then the icon should be that of CBRAIN. Otherwise, it should be a default "globe" URL. 
* When `online-platform-urls` has more than 1 entry, the portal should select an entry containing the string "cbrain" if available. Otherwise, it should select the first entry in the list. If multiple URLs exist that contain the string "cbrain", it should choose the first one.

Pipeline `zenodo.3267250` currently has an `online-platform-urls` property defined with an element containing "cbrain".

## Context
It is the first step toward enabling pipeline execution on CBRAIN, see #63. As part of #58, @shots47s added a CBRAIN URL to `zenodo.3267250` but it is not showing in the portal

## Possible Implementation 

The pipeline JS record reuses the dataset record. The link should be added to the CBRAIN logo there: 
![Screenshot from 2019-07-03 10-37-25](https://user-images.githubusercontent.com/5174953/60601152-9f44bb80-9d7f-11e9-81ec-e761012675e0.png)
If the URL doesn't point to CBRAIN, a generic logo should be used, such as https://fontawesome.com/icons/globe?style=regular

## Related issues
#58 
#63 

@joeyzhou98 would you like to take on this when done with your current task?

**Comment by joeyzhou98** [comment]
@glatard sure this looks like a quick fix, I can take care of it
