### ISSUE TITLE
Refactor the portal app to use blueprints

### ISSUE THREAD

**Issue by shots47s** [CONP-PCNO/conp-portal#71]
## Purpose
Provides a more modular framework to develop Flask Apps by delineating scope within different functions of the App.  For example, the authorization portion can go in its own drop-in authorization app that is added to the main Flask App.

## Context
Sets up the ability to make our overall development more modular, and also provides a path to unit testing of the platform.

## Possible Implementation (optional)
Basically, there is an __init__.py for every app we would like to add that defines a Flask Blueprint.  For example:

In app/auth, the __init__.py will have:

```
from flask import Blueprint
auth_bp = Blueprint('auth',__name__,template_folder='../templates')
from app.auth import routes
```
and then in the app/__init__.py:

```
from app.auth import auth_bp
  app.register_blueprint(auth_bp)
```

Modules like Flask-login are stubbed in the global space, and then a new function called create_app is used to create the full app.

I have an example of what this looks like for a role based authentication scheme using Flask-User at https://github.com/shots47s/NRC-Map-Converter-Flask

**Comment by shots47s** [comment]
Related to #56

**Comment by liamocn** [comment]
Thanks, I can take this on if you wish. Are there other issues to be added to 0.9 in future?

**Comment by shots47s** [comment]
Working through the issues, yes there will be more.
