### ISSUE TITLE
Add cli.py and make proper command line utilities for the app

### ISSUE THREAD

**Issue by shots47s** [CONP-PCNO/conp-portal#72]
## Purpose
Create a place to build command line management tools for the portal such as database operations such as backup, restore, and seeding as well as other functions we may need in the future

## Context
having a succinct place to put these tools can be easier to develop in the future and facilitate testing and translation.

## Possible Implementation (optional)
create a separate cli.py that can be imported into the app and give the proper application context so that testing can also be done on a mock database without rewriting any code or configurations.

Check out what I did in the https://github.com/shots47s/NRC-Map-Converter-Flask for guidance.

## Related issues (optional)
#56

**Comment by jbpoline** [comment]
Would it be a good idea for Dawn to give you a hand with this ?

**Comment by shots47s** [comment]
Sure, in fact, @DESm1th, why don't you take this one and @liamocn take the previous one.

**Comment by DESm1th** [comment]
Will do! I'll start work on this next week when I'm back in Toronto

**Comment by liamocn** [comment]
> 
> 
> Sure, in fact, @DESm1th, why don't you take this one and @liamocn take the previous one.

Works for me!

**Comment by shots47s** [comment]
I have added this, look at app/cli.py, should get us started.

#81
