### ISSUE TITLE
Is a login required for retrieving open data in the portal?

### ISSUE THREAD

**Issue by shots47s** [CONP-PCNO/conp-portal#74]
## Purpose
Do we require a login in the platform to access all of the data, even completely open datasets, or do we require a login or not (independent of what that login is).

## Context
Right now, the portal does not require a login to see and access the data that is unrestricted and open.  It only requires it to see registered data (in the current case, just the PreventAD dataset).  We should decide once and for all, what the model is.  

1. Have users login to use the portal and access all of the data
   a. Advantage: Can track all downloads to an individual user.

2. Have users only need to login to get access to data that is not unrestricted an open
   a. Advantage: More open
   b. Disadvantage: We will only be able to log access to datasets via IP address where the requests are coming from.

**Comment by glatard** [comment]
I prefer 2: 2.a largely outweighs 2.b imo.

**Comment by samirdas** [comment]
My initial vision was to be fully open (no password... i.e. Option 2), but PreventAd insisted on this, even for their open data. I think people are still getting used to the idea of truly open data. Here's one point... we can always eliminate the need to user tracking, by getting rid of the password later, but it's much harder to bring it back. Higher powers will want to weigh in on this. Let's discuss this point at our next authentication meeting.

**Comment by glatard** [comment]
Then their data is registered access and it's still fine. Fully open doesn't prevent us from tracking download numbers, even unique downloads by IP address. It would be funny to have to login to access datasets that are otherwise public, and found for instance on openneuro without the need to login.

**Comment by shots47s** [comment]
Yes, I am not trying to get into an argument about what it means to be open.  It is basically to settle the argument of whether being able to track downloads to people trumped the need to provide the data without login.  I am agnostic, but want a definitive answer from the TSC.  It is very much just an implementation detail.

**Comment by edickie** [comment]
Definitely 2.  It's better to have data downloaded without tracking then left unused/un-found by researchers.

**Comment by shots47s** [comment]
3 votes for 2. (I assume @samirdas was a solid maybe on 2 :))

**Comment by jbpoline** [comment]
I think that would be fine wrt to the preventAD consent given the lastest information I have - but remember that the issue was that in the PrenvenAD consent form we had some language about the dataset being used by the "researchers" or research community IIRC. This was the reason why we were forced -talking to Adrian- to have a orcid login - as orcid can be reasonably argued to be proxy to that community. Also, we should validate with the steering committee.

**Comment by glatard** [comment]
sure but option 2 doesn't prevent datasets that require a login to have one. It just allows datasets that don't require a login to not have to use one.

**Comment by shots47s** [comment]
If you would like to debate how PreventAD requires consent, please open an issue on a different github repo, this is only meant to discuss whether to require a login for all use cases or not.

**Comment by jbpoline** [comment]
The question was whether, without an orcid login, we would have to move that dataset to a "registred" - and this may not be only for PreventAD: I can think of quite a few people would may be happy to push their dataset on conp open if there is an orcid login, but may be not otherwise, so it is really about the general policy, sorry if that was unclear.

**Comment by shots47s** [comment]
The last part is certainly relevant, I just didn't want to make this about PreventAD consent.

**Comment by jbpoline** [comment]
yes, preventAD is only one example (although a big one :)

**Comment by glatard** [comment]
I still don't see why this is an issue for PreventAD. If PreventAD requires a login, it will still be possible. It's just that datasets that don't require a login won't have to have one.

**Comment by shots47s** [comment]
I agree, there may be also people that would be reticent to provide the dataset as open, and feel like we are tracking folks by requiring a login.  So I am inclined to go 2 because it just is more options.  Again, technically all easy, just need for a definitive direction to be made, right now, 2 seems to be the winning option.

**Comment by tomgee** [comment]
I'd go with (2) as well, but I will note that tracking by IP is definitely a very coarse measure.  In many (most?) institutions, the source IP will simply be the firewall/proxy of the entire research institute.

**Comment by jbpoline** [comment]
@glatard : it not specifically an issue, you are right. Maybe the solution is to implement this additional layer:
- layer 0: no login required, all metadata and some datasets
- layer 1: orcid individual
- layer 2: registred access: orcid institutional + white listed 
- layer 3: white listed

That sounds a lot though. Also, just to let you know, from a thread of the steering committee some are strongly pushing for a login even with open data, mostly for traceability as far as I understand (havent read fully the thread). My suggestion is that we come up with a proposal and let the SC decide.

**Comment by shots47s** [comment]
Ok, do you want to bring it to them or shall I? This needs to be resolved quickly.  Otherwise, I suggest we proceed with two and turn on all datasets as registered with ORCID if we have to shift.

Thanks all for the great discussion.

**Comment by shots47s** [comment]
@jbpoline do you have a response to my previous question?

**Comment by shots47s** [comment]
Hi all, in discussions with members of the overall Steering Committee, they are indicating that there is a desire to have it be a requirement to sign up for an account to access the data through the portal.  This is easy and personally, I don't think it is a big requirement.  So I think we should do this, they seem to think it is very important for funding going forward.

Now, if we make the data available through other means (i.e. they could theoretically just download it from datalad directly), I am not sure at all how we would track such usage, in fact, I am not sure we can at all.  

Any thoughts on this from the team?

**Comment by glatard** [comment]
The hosting platforms should track the download. The central portal could only count those downloads initiated from the central portal.

**Comment by jbpoline** [comment]
I'd say search would be done on the metadata, and those should not require login. We can try to push back on the steering committee but there were fairly strong opinions - the possible advantage is that we may get a bit more adoption on the push side with people happier to make data available in that context. 
Question: should we push back ?

**Comment by glatard** [comment]
Let's not push back and focus on doing it. Removing auth would be easy anyway and as @shots47s says it has to be implemented anyway.

**Comment by shots47s** [comment]
I agree, lets freeze this and have it as the POR for the beta, we can always remove it.

**Comment by jbpoline** [comment]
sounds good
JB

**Comment by shots47s** [comment]
Final decision is to require a login to download any datasets, and we will advocate later to remove this if it still desired.
