### ISSUE TITLE
Adopt PEP8 coding standard for the project

### ISSUE THREAD

**Issue by shots47s** [CONP-PCNO/conp-portal#78]
## Purpose
It would behoove us to adopt a coding standard to ensure that our code is well written and extensible.  I am open to suggestions, but PEP8 is pretty standard for Python based projects.  This would require us to run pep8 on code before we accept pull request.  

https://www.python.org/dev/peps/pep-0008/
https://pypi.org/project/pep8/

Any opinions?

## Context
Coding standards are good!

**Comment by jbpoline** [comment]
+1 on this
Also: can we recommend https://www.pylint.org/

**Comment by shots47s** [comment]
Ok, I merged the PR and will now create a branch where we can work on PEP8 compliance.  We should probably focus on this for the next few days so that we can get all of the code up to date moving forward.

**Comment by shots47s** [comment]
added pep8_compliance branch

**Comment by shots47s** [comment]
Also, I think we should exercise the option for up to 99 character lines, 79 is too short.

**Comment by shots47s** [comment]
Have added this to the Travis CI. 

To test your code, you can use:
`pycodestyle --max-line-length=99 app/*.py app/*/*.py`

If this fails, so will TravisCI, need to update to find all python files with a find command, cause I am not a bash genius :)
