### ISSUE TITLE
Improve test coverage in pytest

### ISSUE THREAD

**Issue by liamocn** [CONP-PCNO/conp-portal#89]
## Purpose
Having added the framework for testing the project, tests must now be added to increase overall test coverage

## Context
Test coverage can be monitored using coveralls, which has been added as part of #56

## Related issues (optional)
#56

**Comment by cmadjar** [comment]
@liamocn any update on that issue?

**Comment by liamocn** [comment]
@cmadjar We added a bunch of tests around the time this issue was opened, but the nature of testing is that you can always use more. I'd leave this open for now and I can work on some of the areas where testing could be improved when I get the time.

**Comment by cmadjar** [comment]
Discussed at the CONP dev call of September 30th, 2020.

@liamocn will give a conceptualization demo of the test to be implemented for the portal at the next CONP dev call (October 7th)
