### ISSUE TITLE
Add login pages to the styleguide

### ISSUE THREAD

**Issue by shots47s** [CONP-PCNO/conp-portal#92]
## Purpose
The login pages have a different base and need to be introduced into the styleguide.
## Context
So that we have a definitive styleguide for the whole website.

## Related issues (optional)
#88

**Comment by cmadjar** [comment]
@liamocn @glatard Is this still a current issue? I don't think there is any login functionality on the portal at the moment so I am not sure this ticket is relevant anymore.
